Repository Poor-To-Rich/backend, pull requests merged in 2025-09, with the labels that each got.

#503 [#502] 채팅 메시지 발행 검증 로직 강화
  src/main/java/com/poortorich/chat/realtime/facade/ChatRealTimeFacade.java
  src/main/java/com/poortorich/chat/validator/ChatroomValidator.java
Labels: 🐞BugFix, ✨Feature, 🛜WebSocket

#508 [#507] 모두 읽음 처리 오류 수정
  src/main/java/com/poortorich/chat/controller/ChatController.java
  src/main/java/com/poortorich/chat/model/MarkAllChatroomAsReadResult.java
  src/main/java/com/poortorich/chat/model/UnreadChatInfo.java
  src/main/java/com/poortorich/chat/realtime/facade/ChatRealTimeFacade.java
  src/main/java/com/poortorich/chat/repository/UnreadChatMessageRepository.java
  src/main/java/com/poortorich/chat/service/UnreadChatMessageService.java
Labels: 🐞BugFix, ✨Feature, 🛜WebSocket

#501 [#500] 참여중인 채팅방 오류 수정
  src/main/java/com/poortorich/chat/util/mapper/ChatMessageContentMapper.java
  src/main/java/com/poortorich/chat/util/mapper/ChatroomMapper.java
Labels: 🐞BugFix, ✨Feature, 🛠️Refactor, 📬API, 🛜WebSocket

#510 [#509] 강제 퇴장 로직 수정
  src/main/java/com/poortorich/chat/constants/ChatResponseMessage.java
  src/main/java/com/poortorich/chat/controller/ChatController.java
  src/main/java/com/poortorich/chat/entity/ChatParticipant.java
  src/main/java/com/poortorich/chat/entity/enums/MessageType.java
  src/main/java/com/poortorich/chat/facade/ChatFacade.java
  src/main/java/com/poortorich/chat/realtime/builder/SystemMessageBuilder.java
  src/main/java/com/poortorich/chat/realtime/event/chatparticipants/KickChatroomEvent.java
  src/main/java/com/poortorich/chat/realtime/event/chatparticipants/KickChatroomEventListener.java
  src/main/java/com/poortorich/chat/realtime/facade/ChatRealTimeFacade.java
  src/main/java/com/poortorich/chat/repository/ChatMessageRepository.java
  src/main/java/com/poortorich/chat/response/enums/ChatResponse.java
  src/main/java/com/poortorich/chat/service/ChatMessageService.java
  src/main/java/com/poortorich/chat/service/ChatParticipantService.java
  src/main/java/com/poortorich/chat/util/mapper/ChatMessageMapper.java
  src/main/java/com/poortorich/chat/validator/ChatParticipantValidator.java
Labels: 🐞BugFix, ✨Feature, 🛜WebSocket

#516 [#515] 채팅방 삭제 로직에 기능 추가
  src/main/java/com/poortorich/chat/util/manager/ChatroomLeaveManager.java
  src/main/java/com/poortorich/report/repository/ReportRepository.java
  src/main/java/com/poortorich/report/service/ReportService.java
Labels: 🐞BugFix, ✨Feature

#522 [#521] PENDING 역할 로그아웃 처리
  src/main/java/com/poortorich/security/config/SecurityConfig.java
Labels: 🐞BugFix

#520 [#517] 회원 탈퇴 로직에서 채팅방 데이터 삭제
  src/main/java/com/poortorich/auth/kakao/service/KakaoService.java
  src/main/java/com/poortorich/chat/controller/ChatController.java
  src/main/java/com/poortorich/chat/facade/ChatFacade.java
  src/main/java/com/poortorich/chat/realtime/facade/ChatRealTimeFacade.java
  src/main/java/com/poortorich/chat/response/AllParticipantsResponse.java
  src/main/java/com/poortorich/chat/response/ChatroomCoverInfoResponse.java
  src/main/java/com/poortorich/chat/response/ProfileResponse.java
  src/main/java/com/poortorich/chat/response/SearchParticipantsResponse.java
  src/main/java/com/poortorich/chat/service/ChatParticipantService.java
  src/main/java/com/poortorich/chat/service/ChatroomLeaveService.java
  src/main/java/com/poortorich/chat/service/ChatroomService.java
  src/main/java/com/poortorich/chat/util/ChatBuilder.java
  src/main/java/com/poortorich/chat/util/manager/ChatroomLeaveManager.java
  src/main/java/com/poortorich/chat/util/mapper/ParticipantProfileMapper.java
  src/main/java/com/poortorich/chatnotice/facade/ChatNoticeFacade.java
  src/main/java/com/poortorich/chatnotice/response/NoticeDetailsResponse.java
  src/main/java/com/poortorich/chatnotice/util/ChatNoticeBuilder.java
  src/main/java/com/poortorich/chatnotice/util/mapper/ChatNoticeDataMapper.java
  src/main/java/com/poortorich/ranking/facade/RankingFacade.java
  src/main/java/com/poortorich/ranking/payload/response/RankingResponsePayload.java
  src/main/java/com/poortorich/ranking/response/LatestRankingResponse.java
  src/main/java/com/poortorich/ranking/response/RankingInfoResponse.java
  src/main/java/com/poortorich/ranking/util/RankingBuilder.java
  src/main/java/com/poortorich/ranking/util/mapper/RankerProfileMapper.java
  src/main/java/com/poortorich/user/controller/UserController.java
  src/main/java/com/poortorich/user/entity/User.java
  src/main/java/com/poortorich/user/entity/enums/Role.java
  src/main/java/com/poortorich/user/facade/UserFacade.java
  src/main/java/com/poortorich/user/service/UserResetService.java
  src/main/java/com/poortorich/user/service/UserService.java
Labels: 🐞BugFix, ✨Feature, 📬API, 🛜WebSocket

#531 [#530] 참여중인 채팅방 페이로드 타입 세분화
  src/main/java/com/poortorich/chat/facade/ChatFacade.java
  src/main/java/com/poortorich/chat/realtime/event/chatroom/ChatroomUpdateEvent.java
  src/main/java/com/poortorich/chat/realtime/event/chatroom/ChatroomUpdateEventListener.java
  src/main/java/com/poortorich/chat/realtime/event/chatroom/UserChatroomUpdateEvent.java
  src/main/java/com/poortorich/chat/realtime/event/chatroom/detector/ChatroomUpdateDetector.java
  src/main/java/com/poortorich/chat/realtime/facade/ChatRealTimeFacade.java
  src/main/java/com/poortorich/chat/realtime/payload/response/enums/PayloadType.java
  src/main/java/com/poortorich/chat/service/ChatroomLeaveService.java
Labels: ✨Feature, 🛠️Refactor, 🛜WebSocket

#543 [#542] 사진이 없는 경우 빈 배열 반환 로직 추가
  src/main/java/com/poortorich/photo/facade/PhotoFacade.java
  src/main/java/com/poortorich/photo/util/PhotoBuilder.java
  src/test/java/com/poortorich/photo/facade/PhotoFacadeTest.java
Labels: 🐞BugFix

#545 [#544] 백엔드 서버 배포
  src/main/java/com/poortorich/chat/constants/ChatResponseMessage.java
  src/main/java/com/poortorich/chat/controller/ChatController.java
  src/main/java/com/poortorich/chat/realtime/facade/ChatRealTimeFacade.java
  src/main/java/com/poortorich/chat/repository/ChatMessageRepository.java
  src/main/java/com/poortorich/chat/response/enums/ChatResponse.java
  src/main/java/com/poortorich/chat/service/ChatMessageService.java
  src/main/java/com/poortorich/chat/service/ChatParticipantService.java
  src/main/java/com/poortorich/chat/service/ChatroomLeaveService.java
  src/main/java/com/poortorich/photo/facade/PhotoFacade.java
  src/main/java/com/poortorich/photo/util/PhotoBuilder.java
  src/test/java/com/poortorich/photo/facade/PhotoFacadeTest.java
Labels: 🌏Deploy

#548 [#526] 전체 채팅방 필터링 로직 수정
  src/main/java/com/poortorich/chat/facade/ChatFacade.java
  src/main/java/com/poortorich/chat/repository/ChatroomRepository.java
  src/main/java/com/poortorich/chat/repository/RedisChatRepository.java
  src/main/java/com/poortorich/chat/service/ChatroomService.java
  src/test/java/com/poortorich/chat/service/ChatroomServiceTest.java
Labels: 🛠️Refactor

#550 [#549] 백엔드 서버 배포
  src/main/java/com/poortorich/auth/jwt/util/JwtTokenManager.java
  src/main/java/com/poortorich/auth/service/AuthService.java
  src/main/java/com/poortorich/chat/facade/ChatFacade.java
  src/main/java/com/poortorich/chat/repository/ChatroomRepository.java
  src/main/java/com/poortorich/chat/repository/RedisChatRepository.java
  src/main/java/com/poortorich/chat/service/ChatroomService.java
  src/main/java/com/poortorich/user/facade/UserFacade.java
  src/test/java/com/poortorich/auth/controller/AuthControllerTest.java
  src/test/java/com/poortorich/chat/facade/ChatFacadeTest.java
  src/test/java/com/poortorich/chat/service/ChatMessageServiceTest.java
  src/test/java/com/poortorich/chat/service/ChatParticipantServiceTest.java
  src/test/java/com/poortorich/chat/service/ChatroomServiceTest.java
  src/test/java/com/poortorich/chatnotice/controller/ChatNoticeControllerTest.java
  src/test/java/com/poortorich/chatnotice/facade/ChatNoticeFacadeTest.java
  src/test/java/com/poortorich/global/config/BaseSecurityTest.java
  src/test/java/com/poortorich/ranking/controller/RankingControllerTest.java
  src/test/java/com/poortorich/ranking/facade/RankingFacadeTest.java
  src/test/java/com/poortorich/s3/service/FileUploadServiceTest.java
  src/test/java/com/poortorich/s3/util/S3FileUtilsTest.java
  src/test/java/com/poortorich/user/controller/UserControllerTest.java
  src/test/java/com/poortorich/user/facade/UserFacadeTest.java
  src/test/java/com/poortorich/user/validator/enums/PasswordValidationCase.java
Labels: 🌏Deploy

#553 [#552] 참여중인 채팅방 조회 마지막 채팅 메시지 필터 로직 추가
  src/main/java/com/poortorich/chat/entity/ChatParticipant.java
  src/main/java/com/poortorich/chat/realtime/event/chatparticipants/KickChatroomEventListener.java
  src/main/java/com/poortorich/chat/realtime/facade/ChatRealTimeFacade.java
  src/main/java/com/poortorich/chat/repository/ChatMessageRepository.java
  src/main/java/com/poortorich/chat/service/ChatMessageService.java
  src/main/java/com/poortorich/chat/service/ChatParticipantService.java
Labels: 🐞BugFix, ✨Feature

#592 [#591] 랭킹 테스트 로직 삭제
  src/main/java/com/poortorich/chat/service/ChatMessageService.java
  src/main/java/com/poortorich/ranking/controller/RankingController.java
  src/main/java/com/poortorich/ranking/facade/RankingFacade.java
  src/main/java/com/poortorich/ranking/service/RankingService.java
  src/main/java/com/poortorich/ranking/util/calculator/RankingCalculator.java
Labels: 🛠️Refactor

#597 [#596] 이미지 업로드 타입 추가
  src/main/java/com/poortorich/s3/constants/S3ValidationConstraints.java
  src/main/java/com/poortorich/s3/util/WebpConverter.java
Labels: ✨Feature

#598 [#593] 전체채팅방 목록 조회 수정
  src/main/java/com/poortorich/chat/repository/ChatroomRepository.java
  src/main/java/com/poortorich/chat/repository/RedisChatRepository.java
  src/main/java/com/poortorich/chat/service/ChatMessageService.java
  src/test/java/com/poortorich/chat/facade/ChatFacadeTest.java
Labels: 🛠️Refactor

#602 [#600] 참여중인 채팅방 목록 조회 커서 변경에 따른 로직 수정
  src/main/java/com/poortorich/chat/controller/UserChatroomController.java
  src/main/java/com/poortorich/chat/facade/ChatFacade.java
  src/main/java/com/poortorich/chat/model/ChatroomPaginationContext.java
  src/main/java/com/poortorich/chat/repository/ChatMessageRepository.java
  src/main/java/com/poortorich/chat/repository/ChatParticipantRepository.java
  src/main/java/com/poortorich/chat/response/MyChatroomsResponse.java
  src/main/java/com/poortorich/chat/service/ChatMessageService.java
  src/main/java/com/poortorich/chat/service/ChatParticipantService.java
  src/main/java/com/poortorich/chat/util/provider/ChatPaginationProvider.java
Labels: ✨Feature, 🛠️Refactor
