Repository Poor-To-Rich/backend, pull requests merged in 2025-07, with the labels that each got.

#247 [#228] 차트 로직 리팩터링
  src/main/java/com/poortorich/accountbook/constants/AccountBookComparator.java
  src/main/java/com/poortorich/accountbook/entity/AccountBook.java
  src/main/java/com/poortorich/accountbook/repository/AccountBookRepository.java
  src/main/java/com/poortorich/accountbook/service/AccountBookService.java
  src/main/java/com/poortorich/accountbook/util/AccountBookBuilder.java
  src/main/java/com/poortorich/accountbook/util/AccountBookCalculator.java
  src/main/java/com/poortorich/accountbook/util/AccountBookExtractor.java
  src/main/java/com/poortorich/accountbook/util/AccountBookGrouper.java
  src/main/java/com/poortorich/accountbook/util/AccountBookMerger.java
  src/main/java/com/poortorich/chart/aggregator/ChartDataAggregator.java
  src/main/java/com/poortorich/chart/collector/ChartDataCollector.java
  src/main/java/com/poortorich/chart/constants/ChartConstants.java
  src/main/java/com/poortorich/chart/controller/ChartController.java
  src/main/java/com/poortorich/chart/facade/ChartFacade.java
  src/main/java/com/poortorich/chart/factory/ChartResponseFactory.java
  src/main/java/com/poortorich/chart/handler/ChartPaginationHandler.java
  src/main/java/com/poortorich/chart/mapper/ChartDataMapper.java
  src/main/java/com/poortorich/chart/model/domain/ChartDataContext.java
  src/main/java/com/poortorich/chart/model/domain/PaginationResult.java
  src/main/java/com/poortorich/chart/response/CategoryChart.java
  src/main/java/com/poortorich/chart/service/ChartService.java
  src/main/java/com/poortorich/chart/util/AccountBookUtil.java
  src/main/java/com/poortorich/chart/util/PeriodFormatter.java
  src/main/java/com/poortorich/expense/entity/Expense.java
  src/main/java/com/poortorich/global/date/constants/DateConstants.java
  src/main/java/com/poortorich/global/date/domain/DateInfo.java
  src/main/java/com/poortorich/global/date/util/DateInfoProvider.java
  src/main/java/com/poortorich/global/statistics/util/StatCalculator.java
  src/main/java/com/poortorich/income/entity/Income.java
  src/main/java/com/poortorich/page/domain/Pagination.java
  src/main/java/com/poortorich/report/facade/ReportFacade.java
  src/main/java/com/poortorich/report/service/ReportService.java
  src/test/java/com/poortorich/chart/facade/ChartFacadeTest.java
  src/test/java/com/poortorich/chart/service/ChartServiceTest.java
  src/test/java/com/poortorich/global/date/util/DateInfoProviderTest.java
  src/test/java/com/poortorich/global/statistics/fixture/StatCalculatorTestFixture.java
  src/test/java/com/poortorich/global/statistics/util/StatCalculatorTest.java
Labels: 🛠️Refactor, 📬API

#248 [#242] 반복데이터 리팩토링
  Dockerfile
  src/main/java/com/poortorich/iteration/constants/IterationResponseMessages.java
  src/main/java/com/poortorich/iteration/entity/IterationExpenses.java
  src/main/java/com/poortorich/iteration/entity/IterationIncomes.java
  src/main/java/com/poortorich/iteration/entity/info/DailyIterationRule.java
  src/main/java/com/poortorich/iteration/entity/info/IterationInfo.java
  src/main/java/com/poortorich/iteration/entity/info/MonthlyIterationRule.java
  src/main/java/com/poortorich/iteration/entity/info/WeeklyIterationRule.java
  src/main/java/com/poortorich/iteration/entity/info/YearlyIterationRule.java
  src/main/java/com/poortorich/iteration/mapper/IterationMapper.java
  src/main/java/com/poortorich/iteration/provider/IterationCalculatorProvider.java
  src/main/java/com/poortorich/iteration/service/IterationService.java
  src/main/java/com/poortorich/iteration/util/IterationBuilder.java
  src/main/java/com/poortorich/iteration/validator/MonthlyOptionValidator.java
Labels: 🛠️Refactor

#252 [#251] QA 오류 수정
  src/main/java/com/poortorich/category/repository/CategoryRepository.java
  src/main/java/com/poortorich/category/service/CategoryService.java
  src/main/java/com/poortorich/iteration/entity/enums/Weekday.java
  src/main/java/com/poortorich/iteration/provider/IterationCalculatorProvider.java
Labels: 🐞BugFix

#254 [#253] QA 오류 수정
  src/main/java/com/poortorich/accountbook/service/AccountBookService.java
  src/main/java/com/poortorich/auth/service/AuthService.java
  src/main/java/com/poortorich/chart/collector/ChartDataCollector.java
  src/main/java/com/poortorich/chart/facade/ChartFacade.java
  src/main/java/com/poortorich/chart/factory/ChartResponseFactory.java
  src/main/java/com/poortorich/chart/util/PeriodFormatter.java
  src/main/java/com/poortorich/user/controller/UserController.java
  src/main/java/com/poortorich/user/facade/UserFacade.java
  src/main/java/com/poortorich/user/request/EmailUpdateRequest.java
  src/main/java/com/poortorich/user/service/UserService.java
Labels: 🐞BugFix

#256 [#255] 파일 구조 리팩토링
  src/main/java/com/poortorich/accountbook/entity/enums/IterationType.java
  src/main/java/com/poortorich/accountbook/request/AccountBookRequest.java
  src/main/java/com/poortorich/accountbook/response/enums/AccountBookResponse.java
  src/main/java/com/poortorich/accountbook/service/AccountBookService.java
  src/main/java/com/poortorich/category/controller/CategoryController.java
  src/main/java/com/poortorich/category/entity/enums/CategoryType.java
  src/main/java/com/poortorich/category/response/enums/CategoryResponse.java
  src/main/java/com/poortorich/category/service/CategoryService.java
  src/main/java/com/poortorich/expense/controller/ExpenseController.java
  src/main/java/com/poortorich/expense/entity/enums/PaymentMethod.java
  src/main/java/com/poortorich/expense/facade/ExpenseFacade.java
  src/main/java/com/poortorich/expense/response/enums/ExpenseResponse.java
  src/main/java/com/poortorich/iteration/entity/enums/EndType.java
  src/main/java/com/poortorich/iteration/entity/enums/IterationRuleType.java
  src/main/java/com/poortorich/iteration/entity/enums/MonthlyMode.java
  src/main/java/com/poortorich/iteration/entity/enums/Weekday.java
  src/main/java/com/poortorich/iteration/request/End.java
  src/main/java/com/poortorich/iteration/request/IterationRule.java
  src/main/java/com/poortorich/iteration/request/MonthlyOption.java
  src/main/java/com/poortorich/iteration/response/enums/IterationResponse.java
  src/main/java/com/poortorich/iteration/service/IterationService.java
  src/main/java/com/poortorich/iteration/validator/EndValidator.java
  src/main/java/com/poortorich/iteration/validator/IterationRuleValidator.java
  src/main/java/com/poortorich/iteration/validator/MonthlyOptionValidator.java
  src/main/java/com/poortorich/iteration/validator/annotations/EndCheck.java
  src/main/java/com/poortorich/iteration/validator/annotations/IterationRuleCheck.java
  src/main/java/com/poortorich/iteration/validator/annotations/MonthlyOptionCheck.java
  src/test/java/com/poortorich/expense/controller/ExpenseControllerTest.java
Labels: 🛠️Refactor

#262 [#261] 카테고리 편집 오류 수정
  src/main/java/com/poortorich/category/repository/CategoryRepository.java
  src/main/java/com/poortorich/category/service/CategoryService.java
Labels: 🐞BugFix

#266 [#265] 회원 역할 조회 및 수정 API
  src/main/java/com/poortorich/admin/constants/AdminResponseMessage.java
  src/main/java/com/poortorich/admin/controller/AdminController.java
  src/main/java/com/poortorich/admin/facade/AdminFacade.java
  src/main/java/com/poortorich/admin/request/UserRoleUpdateRequest.java
  src/main/java/com/poortorich/admin/response/enums/AdminResponse.java
  src/main/java/com/poortorich/admin/service/UserManagementService.java
  src/main/java/com/poortorich/security/config/SecurityConfig.java
  src/main/java/com/poortorich/user/constants/UserResponseMessages.java
  src/main/java/com/poortorich/user/controller/UserController.java
  src/main/java/com/poortorich/user/entity/User.java
  src/main/java/com/poortorich/user/entity/enums/Role.java
  src/main/java/com/poortorich/user/facade/UserFacade.java
  src/main/java/com/poortorich/user/response/UserRoleResponse.java
  src/main/java/com/poortorich/user/response/enums/UserResponse.java
Labels: ✨Feature, 📬API

#281 [#280] 차트 상세 내역 중복 데이터 조회 수정
  src/main/java/com/poortorich/page/domain/Pagination.java
Labels: 🐞BugFix

#296 [#295] 가계부 편집 오류 수정
  src/main/java/com/poortorich/category/repository/CategoryRepository.java
  src/main/java/com/poortorich/category/service/CategoryService.java
  src/main/java/com/poortorich/expense/facade/ExpenseFacade.java
  src/main/java/com/poortorich/income/facade/IncomeFacade.java
  src/test/java/com/poortorich/expense/facade/ExpenseFacadeTest.java
Labels: 🐞BugFix

#299 [#298] CORS 설정 추가
  src/main/java/com/poortorich/security/constants/SecurityConstants.java
Labels: ⚙️Setting

#303 [#302] OAuth 회원 상세 조회 API 요구사항 적용
  src/main/java/com/poortorich/auth/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/poortorich/s3/constants/S3Constants.java
  src/main/java/com/poortorich/user/controller/UserController.java
  src/main/java/com/poortorich/user/facade/UserFacade.java
  src/main/java/com/poortorich/user/response/OAuthUserDetailResponse.java
  src/main/java/com/poortorich/user/service/UserService.java
Labels: 🛠️Refactor

#284 [#283] 액세스 토큰 Bearer 접두사 삭제
  src/main/java/com/poortorich/auth/service/AuthService.java
Labels: 🛠️Refactor

#305 [#304] 카카오 로그인 리다이렉션 경로 수정
  src/main/java/com/poortorich/auth/oauth2/handler/CustomOAuth2LoginSuccessHandler.java
Labels: 🛠️Refactor

#310 [#309] 회원탈퇴 시 카카오 연결 해제 로직 추가
  build.gradle
  docker-compose.yml
  src/main/java/com/poortorich/auth/kakao/service/KakaoService.java
  src/main/java/com/poortorich/user/facade/UserFacade.java
  src/main/resources/application.properties
Labels: ✨Feature, ⚙️Setting, 📬API

#313 [#306] 카테고리 테스트코드 작성
  src/test/java/com/poortorich/category/controller/CategoryControllerTest.java
  src/test/java/com/poortorich/category/fixture/CategoryApiFixture.java
  src/test/java/com/poortorich/category/fixture/CategoryFixture.java
  src/test/java/com/poortorich/category/service/CategoryServiceTest.java
  src/test/java/com/poortorich/category/util/CategoryTestBuilder.java
Labels: ✔️Test

#315 [#314] entity 필드명 수정
  src/main/java/com/poortorich/category/entity/Category.java
  src/main/java/com/poortorich/expense/entity/Expense.java
  src/main/java/com/poortorich/income/entity/Income.java
  src/main/java/com/poortorich/iteration/entity/IterationExpenses.java
  src/main/java/com/poortorich/iteration/entity/IterationIncomes.java
  src/main/java/com/poortorich/iteration/entity/info/IterationInfo.java
  src/main/java/com/poortorich/iteration/entity/info/MonthlyIterationRule.java
  src/main/java/com/poortorich/iteration/entity/info/WeeklyIterationRule.java
  src/main/java/com/poortorich/user/entity/User.java
Labels: 🛠️Refactor

#317 [#312] 웹소켓 검증 로직 추가
  src/main/java/com/poortorich/websocket/chat/controller/ChatController.java
  src/main/java/com/poortorich/websocket/chat/request/ChatMessageRequest.java
  src/main/java/com/poortorich/websocket/config/WebSocketConfig.java
  src/main/java/com/poortorich/websocket/stomp/command/connect/handler/StompConnectHandler.java
  src/main/java/com/poortorich/websocket/stomp/command/disconnect/handler/StompDisconnectHandler.java
  src/main/java/com/poortorich/websocket/stomp/command/publish/endpoint/PublishEndpoint.java
  src/main/java/com/poortorich/websocket/stomp/command/publish/handler/StompSendHandler.java
  src/main/java/com/poortorich/websocket/stomp/command/publish/validator/StompPublishValidator.java
  src/main/java/com/poortorich/websocket/stomp/command/subscribe/endpoint/SubscribeEndpoint.java
  src/main/java/com/poortorich/websocket/stomp/command/subscribe/handler/StompSubscribeHandler.java
  src/main/java/com/poortorich/websocket/stomp/command/subscribe/util/SubscribeEndpointExtractor.java
  src/main/java/com/poortorich/websocket/stomp/command/subscribe/validator/SubscribeValidator.java
  src/main/java/com/poortorich/websocket/stomp/constants/StompResponseMessage.java
  src/main/java/com/poortorich/websocket/stomp/interceptor/StompInterceptor.java
  src/main/java/com/poortorich/websocket/stomp/response/StompResponse.java
  src/main/java/com/poortorich/websocket/stomp/util/StompHeaderExtractor.java
  src/main/java/com/poortorich/websocket/stomp/util/StompSessionManager.java
  src/main/java/com/poortorich/websocket/stomp/validator/StompValidator.java
Labels: ✨Feature, 🛜WebSocket

#322 [#316] 채팅방 추가 API 수정사항
  src/main/java/com/poortorich/chat/controller/ChatController.java
  src/main/java/com/poortorich/chat/entity/ChatMessage.java
  src/main/java/com/poortorich/chat/facade/ChatFacade.java
  src/main/java/com/poortorich/chat/request/ChatroomCreateRequest.java
  src/main/java/com/poortorich/tag/service/TagService.java
  src/test/java/com/poortorich/chat/facade/ChatFacadeTest.java
  src/test/java/com/poortorich/chat/service/ChatroomServiceTest.java
Labels: 🛠️Refactor, 📬API

#328 [#325] 채팅방 조회 API 구현
  src/main/java/com/poortorich/chat/constants/ChatResponseMessage.java
  src/main/java/com/poortorich/chat/controller/ChatController.java
  src/main/java/com/poortorich/chat/facade/ChatFacade.java
  src/main/java/com/poortorich/chat/realtime/facade/ChatRealTimeFacade.java
  src/main/java/com/poortorich/chat/response/ChatroomInfoResponse.java
  src/main/java/com/poortorich/chat/response/enums/ChatResponse.java
  src/main/java/com/poortorich/chat/service/ChatroomService.java
  src/main/java/com/poortorich/chat/util/ChatBuilder.java
  src/main/java/com/poortorich/tag/repository/TagRepository.java
  src/main/java/com/poortorich/tag/service/TagService.java
  src/test/java/com/poortorich/chat/controller/ChatControllerTest.java
  src/test/java/com/poortorich/chat/facade/ChatFacadeTest.java
  src/test/java/com/poortorich/chat/service/ChatroomServiceTest.java
  src/test/java/com/poortorich/tag/service/TagServiceTest.java
Labels: ✨Feature, 📬API
