Repository Poor-To-Rich/backend, pull requests merged in 2025-06, with the labels that each got.

#112 [#109] 카테고리 구간 내역 조회
  src/main/java/com/poortorich/accountbook/entity/AccountBook.java
  src/main/java/com/poortorich/accountbook/enums/AccountBookType.java
  src/main/java/com/poortorich/accountbook/repository/AccountBookRepository.java
  src/main/java/com/poortorich/accountbook/request/AccountBookRequest.java
  src/main/java/com/poortorich/accountbook/service/AccountBookService.java
  src/main/java/com/poortorich/accountbook/util/AccountBookBuilder.java
  src/main/java/com/poortorich/accountbook/util/AccountBookCostExtractor.java
  src/main/java/com/poortorich/category/service/CategoryService.java
  src/main/java/com/poortorich/chart/constants/ChartResponseMessage.java
  src/main/java/com/poortorich/chart/controller/ChartController.java
  src/main/java/com/poortorich/chart/facade/ChartFacade.java
  src/main/java/com/poortorich/chart/response/CategoryLog.java
  src/main/java/com/poortorich/chart/response/CategorySectionResponse.java
  src/main/java/com/poortorich/chart/response/TransactionRecord.java
  src/main/java/com/poortorich/chart/response/enums/ChartResponse.java
  src/main/java/com/poortorich/chart/service/ChartService.java
  src/main/java/com/poortorich/chart/util/TransactionUtil.java
  src/main/java/com/poortorich/expense/entity/Expense.java
  src/main/java/com/poortorich/expense/facade/ExpenseFacade.java
  src/main/java/com/poortorich/expense/repository/ExpenseRepository.java
  src/main/java/com/poortorich/expense/service/ExpenseService.java
  src/main/java/com/poortorich/expense/util/ExpenseCostExtractor.java
  src/main/java/com/poortorich/income/entity/Income.java
  src/main/java/com/poortorich/income/facade/IncomeFacade.java
  src/main/java/com/poortorich/income/repository/IncomeRepository.java
  src/main/java/com/poortorich/income/service/IncomeService.java
  src/test/java/com/poortorich/chart/controller/ChartControllerTest.java
  src/test/java/com/poortorich/chart/service/ChartServiceTest.java
  src/test/java/com/poortorich/expense/util/AccountBookCostExtractorTest.java
Labels: ✨Feature, 🛠️Refactor, ✔️Test, 📬API

#114 [#113] 지출 카테고리 차트 API
  src/main/java/com/poortorich/chart/constants/ChartResponseMessage.java
  src/main/java/com/poortorich/chart/controller/ChartController.java
  src/main/java/com/poortorich/chart/facade/ChartFacade.java
  src/main/java/com/poortorich/chart/response/CategoryChart.java
  src/main/java/com/poortorich/chart/response/CategoryChartResponse.java
  src/main/java/com/poortorich/chart/response/enums/ChartResponse.java
  src/main/java/com/poortorich/chart/service/ChartService.java
  src/main/java/com/poortorich/chart/util/AccountBookUtil.java
  src/main/java/com/poortorich/chart/util/TransactionUtil.java
  src/main/java/com/poortorich/global/statistics/util/StatCalculator.java
  src/test/java/com/poortorich/chart/facade/ChartFacadeTest.java
  src/test/java/com/poortorich/expense/facade/ExpenseFacadeTest.java
  src/test/java/com/poortorich/global/statistics/util/StatCalculatorTest.java
Labels: ✨Feature, 📬API

#121 [#120] 반복 지출 데이터 조회 API
  src/main/java/com/poortorich/accountbook/response/AccountBookInfoResponse.java
  src/main/java/com/poortorich/accountbook/response/IterationDetailsResponse.java
  src/main/java/com/poortorich/accountbook/service/AccountBookService.java
  src/main/java/com/poortorich/expense/constants/ExpenseResponseMessages.java
  src/main/java/com/poortorich/expense/controller/ExpenseController.java
  src/main/java/com/poortorich/expense/facade/ExpenseFacade.java
  src/main/java/com/poortorich/expense/response/ExpenseResponse.java
  src/main/java/com/poortorich/iteration/repository/IterationExpensesRepository.java
  src/main/java/com/poortorich/iteration/repository/IterationRepository.java
  src/main/java/com/poortorich/iteration/service/IterationService.java
Labels: ✨Feature, 📬API

#123 [#119] 수입 가계부 편집 API 구현
  src/main/java/com/poortorich/accountbook/entity/AccountBook.java
  src/main/java/com/poortorich/accountbook/service/AccountBookService.java
  src/main/java/com/poortorich/expense/entity/Expense.java
  src/main/java/com/poortorich/expense/facade/ExpenseFacade.java
  src/main/java/com/poortorich/expense/service/ExpenseService.java
  src/main/java/com/poortorich/income/constants/IncomeResponseMessages.java
  src/main/java/com/poortorich/income/controller/IncomeController.java
  src/main/java/com/poortorich/income/entity/Income.java
  src/main/java/com/poortorich/income/facade/IncomeFacade.java
  src/main/java/com/poortorich/income/response/enums/IncomeResponse.java
  src/main/java/com/poortorich/income/service/IncomeService.java
  src/main/java/com/poortorich/iteration/entity/Iteration.java
  src/main/java/com/poortorich/iteration/entity/IterationExpenses.java
  src/main/java/com/poortorich/iteration/entity/IterationIncomes.java
  src/main/java/com/poortorich/iteration/repository/IterationExpensesRepository.java
  src/main/java/com/poortorich/iteration/repository/IterationIncomesRepository.java
  src/main/java/com/poortorich/iteration/repository/IterationRepository.java
  src/main/java/com/poortorich/iteration/service/IterationService.java
Labels: ✨Feature, 🛠️Refactor, 📬API

#133 [#127] 카테고리 꺾은선 그래프 API
  src/main/java/com/poortorich/accountbook/repository/AccountBookRepository.java
  src/main/java/com/poortorich/accountbook/service/AccountBookService.java
  src/main/java/com/poortorich/chart/constants/ChartResponseMessage.java
  src/main/java/com/poortorich/chart/controller/ChartController.java
  src/main/java/com/poortorich/chart/facade/ChartFacade.java
  src/main/java/com/poortorich/chart/response/CategoryLineResponse.java
  src/main/java/com/poortorich/chart/response/enums/ChartResponse.java
  src/main/java/com/poortorich/chart/service/ChartService.java
  src/main/java/com/poortorich/chart/util/PeriodFormatter.java
  src/main/java/com/poortorich/expense/repository/ExpenseRepository.java
  src/main/java/com/poortorich/global/date/constants/DateResponseMessage.java
  src/main/java/com/poortorich/global/date/response/enums/DateResponse.java
  src/main/java/com/poortorich/income/repository/IncomeRepository.java
Labels: ✨Feature, 📬API

#134 [#126] 일별 상세 내역 API 구현
  src/main/java/com/poortorich/accountbook/entity/AccountBook.java
  src/main/java/com/poortorich/accountbook/service/AccountBookService.java
  src/main/java/com/poortorich/accountbook/util/AccountBookBuilder.java
  src/main/java/com/poortorich/global/date/util/DateParser.java
  src/main/java/com/poortorich/income/entity/Income.java
  src/main/java/com/poortorich/report/constants/ReportResponseMessages.java
  src/main/java/com/poortorich/report/controller/ReportController.java
  src/main/java/com/poortorich/report/facade/ReportFacade.java
  src/main/java/com/poortorich/report/response/DailyDetailsResponse.java
  src/main/java/com/poortorich/report/response/enums/ReportResponse.java
  src/main/java/com/poortorich/report/service/ReportService.java
Labels: ✨Feature, 🛠️Refactor, 📬API

#136 [#135] 수입 가계부 삭제 API 구현
  src/main/java/com/poortorich/accountbook/request/AccountBookDeleteRequest.java
  src/main/java/com/poortorich/expense/controller/ExpenseController.java
  src/main/java/com/poortorich/expense/facade/ExpenseFacade.java
  src/main/java/com/poortorich/expense/service/ExpenseService.java
  src/main/java/com/poortorich/income/constants/IncomeResponseMessages.java
  src/main/java/com/poortorich/income/controller/IncomeController.java
  src/main/java/com/poortorich/income/facade/IncomeFacade.java
  src/main/java/com/poortorich/income/response/enums/IncomeResponse.java
  src/test/java/com/poortorich/expense/service/ExpenseServiceTest.java
Labels: ✨Feature, 🛠️Refactor, 📬API

#137 [#129] 수입 총액 및 저축 총액 조회 API
  src/main/java/com/poortorich/accountbook/service/AccountBookService.java
  src/main/java/com/poortorich/chart/constants/ChartResponseMessage.java
  src/main/java/com/poortorich/chart/controller/ChartController.java
  src/main/java/com/poortorich/chart/facade/ChartFacade.java
  src/main/java/com/poortorich/chart/response/enums/ChartResponse.java
  src/main/java/com/poortorich/chart/service/ChartService.java
  src/main/java/com/poortorich/income/response/enums/IncomeResponse.java
  src/test/java/com/poortorich/chart/controller/ChartControllerTest.java
  src/test/java/com/poortorich/chart/facade/ChartFacadeTest.java
  src/test/java/com/poortorich/chart/service/ChartServiceTest.java
Labels: ✨Feature, 📬API

#142 [#138] 카테고리 이름 중복 검사 로직 수정
  src/main/java/com/poortorich/category/entity/enums/CategoryType.java
  src/main/java/com/poortorich/category/repository/CategoryRepository.java
  src/main/java/com/poortorich/category/service/CategoryService.java
Labels: 🛠️Refactor

#150 [#132] 회원탈퇴 API
  src/main/java/com/poortorich/user/constants/UserResponseMessages.java
  src/main/java/com/poortorich/user/controller/UserController.java
  src/main/java/com/poortorich/user/facade/UserFacade.java
  src/main/java/com/poortorich/user/response/enums/UserResponse.java
  src/main/java/com/poortorich/user/service/UserResetService.java
  src/main/java/com/poortorich/user/service/UserService.java
Labels: ✨Feature, 📬API

#151 feat: 월별 수입/지출 합계 API
  src/main/java/com/poortorich/report/constants/ReportResponseMessages.java
  src/main/java/com/poortorich/report/controller/ReportController.java
  src/main/java/com/poortorich/report/facade/ReportFacade.java
  src/main/java/com/poortorich/report/response/DailyFinance.java
  src/main/java/com/poortorich/report/response/MonthlyTotalResponse.java
  src/main/java/com/poortorich/report/response/enums/ReportResponse.java
  src/main/java/com/poortorich/report/service/ReportService.java
Labels: ✨Feature, 📬API

#157 [#156] 이메일 인증 로직에서 이메일 중복 확인 추가
  src/main/java/com/poortorich/email/facade/EmailFacade.java
Labels: ✨Feature, 📬API

#167 [#166] 기본 카테고리 조회 응답 필드 추가
  src/main/java/com/poortorich/category/response/DefaultCategoryResponse.java
  src/main/java/com/poortorich/category/service/CategoryService.java
Labels: 🛠️Refactor

#169 [#168] 활성화된 카테고리 목록 조회 로직 수정
  src/main/java/com/poortorich/category/repository/CategoryRepository.java
  src/main/java/com/poortorich/category/service/CategoryService.java
Labels: 🛠️Refactor

#171 [#170] 반복데이터 확인 필드 추가
  src/main/java/com/poortorich/accountbook/entity/enums/IterationType.java
  src/main/java/com/poortorich/accountbook/response/AccountBookInfoResponse.java
  src/main/java/com/poortorich/accountbook/util/AccountBookBuilder.java
Labels: ✨Feature, 🛠️Refactor

#173 [#172] 존재하지 않는 수입 가계부 응답 수정
  src/main/java/com/poortorich/accountbook/service/AccountBookService.java
  src/main/java/com/poortorich/income/constants/IncomeResponseMessages.java
  src/main/java/com/poortorich/income/response/enums/IncomeResponse.java
Labels: 🛠️Refactor

#177 [#176] 월별 수입지출 명세 응답 빌드 수정
  src/main/java/com/poortorich/report/facade/ReportFacade.java
Labels: 🛠️Refactor

#183 [#182] Gender 한글 포맷팅 로직 삭제
  src/main/java/com/poortorich/user/entity/enums/Gender.java
Labels: 🛠️Refactor

#190 [#189] 기본 지출 카테고리 이름 오타 수정
  src/main/java/com/poortorich/category/domain/model/enums/DefaultExpenseCategory.java
Labels: 🛠️Refactor

#192 [#191] 금액 포맷팅 단위 추가
  src/main/java/com/poortorich/chart/response/PeriodTotal.java
  src/main/java/com/poortorich/chart/service/ChartService.java
  src/main/java/com/poortorich/chart/util/AmountFormatter.java
Labels: ✨Feature, 🛠️Refactor

#198 [#197] 프로필 상세 조회 때 isDefaultProfile 추가
  src/main/java/com/poortorich/user/response/UserDetailResponse.java
  src/main/java/com/poortorich/user/service/UserService.java
Labels: ✨Feature, 🛠️Refactor

#188 [#178] 주별 수입/지출 상세내역 수정
  src/main/java/com/poortorich/accountbook/service/AccountBookService.java
  src/main/java/com/poortorich/chart/util/PeriodFormatter.java
  src/main/java/com/poortorich/report/facade/ReportFacade.java
  src/main/java/com/poortorich/report/service/ReportService.java
Labels: 🛠️Refactor

#200 [#199] 반복 지출/수입 데이터 조회 수정
  src/main/java/com/poortorich/expense/facade/ExpenseFacade.java
  src/main/java/com/poortorich/income/facade/IncomeFacade.java
  src/main/java/com/poortorich/iteration/repository/IterationExpensesRepository.java
  src/main/java/com/poortorich/iteration/repository/IterationIncomesRepository.java
  src/main/java/com/poortorich/iteration/repository/IterationRepository.java
  src/main/java/com/poortorich/iteration/service/IterationService.java
Labels: 🐞BugFix, 🛠️Refactor

#204 [#203] 활성화된 카테고리 정렬 방식 수정
  src/main/java/com/poortorich/category/service/CategoryService.java
Labels: 🛠️Refactor

#202 [#201] 가계부 추가/편집 카테고리 조회 로직 변경
  src/main/java/com/poortorich/category/service/CategoryService.java
  src/main/java/com/poortorich/expense/facade/ExpenseFacade.java
  src/main/java/com/poortorich/income/facade/IncomeFacade.java
Labels: 🐞BugFix, 🛠️Refactor

#206 [#205] 가계부 추가 응답 데이터 추가
  src/main/java/com/poortorich/accountbook/response/AccountBookCreateResponse.java
  src/main/java/com/poortorich/expense/controller/ExpenseController.java
  src/main/java/com/poortorich/expense/facade/ExpenseFacade.java
  src/main/java/com/poortorich/income/controller/IncomeController.java
  src/main/java/com/poortorich/income/facade/IncomeFacade.java
  src/test/java/com/poortorich/expense/controller/ExpenseControllerTest.java
Labels: ✨Feature, 🛠️Refactor

#208 [#207] AccountBookInfo 응답에 날짜 필드 추가
  src/main/java/com/poortorich/accountbook/response/AccountBookInfoResponse.java
  src/main/java/com/poortorich/accountbook/util/AccountBookBuilder.java
Labels: ✨Feature

#215 [#214] aggregatedData 비율 조정
  src/main/java/com/poortorich/chart/facade/ChartFacade.java
Labels: ✨Feature, 🛠️Refactor

#217 [#216] 프로필 조회시 기본프로필인 경우 null로 제공
  src/main/java/com/poortorich/user/service/UserService.java
Labels: ✨Feature, 🛠️Refactor, 📬API

#219 [#218] 프로필 편집 버그 수정
  src/main/java/com/poortorich/s3/constants/S3Constants.java
  src/main/java/com/poortorich/s3/service/FileUploadService.java
Labels: 🐞BugFix

#221 [#220] 주별 상세 내역 응답값 수정
  src/main/java/com/poortorich/accountbook/service/AccountBookService.java
  src/main/java/com/poortorich/report/facade/ReportFacade.java
  src/main/java/com/poortorich/report/service/ReportService.java
Labels: 🛠️Refactor

#231 [#230] 로깅 재설정
  src/main/java/com/poortorich/global/aop/LogAspect.java
Labels: 🐞BugFix

#233 [#232] 로그 설정 변경
  src/main/java/com/poortorich/global/aop/LogAspect.java
Labels: ⚙️Setting

#235 [#234] 카테고리 구간 내역 총 내역 수 조회 로직 수정
  src/main/java/com/poortorich/accountbook/service/AccountBookService.java
  src/main/java/com/poortorich/chart/facade/ChartFacade.java
Labels: ✨Feature, 🛠️Refactor, 📬API

#246 [#245] 로그인 테스트 코드 오류 수정
  src/test/java/com/poortorich/auth/service/AuthServiceTest.java
Labels: 🐞BugFix, ✔️Test
