Repository Poor-To-Rich/backend, pull requests merged in 2025-05, with the labels that each got.

#59 [#57] 카테고리 응답 형식 수정
  src/main/java/com/poortorich/category/constants/CategoryResponseMessage.java
  src/main/java/com/poortorich/category/controller/CategoryController.java
  src/main/java/com/poortorich/category/entity/CategoryType.java
  src/main/java/com/poortorich/category/request/CategoryInfoRequest.java
  src/main/java/com/poortorich/category/response/CategoryResponse.java
  src/main/java/com/poortorich/category/service/CategoryService.java
Labels: 🛠️Refactor

#64 [#63] 프론트엔드 CORS 설정
  src/main/java/com/poortorich/security/constants/SecurityConstants.java
Labels: 🐞BugFix, 🌏Deploy

#61 [#60] 카테고리 로직 수정
  src/main/java/com/poortorich/category/controller/CategoryController.java
  src/main/java/com/poortorich/category/entity/Category.java
  src/main/java/com/poortorich/category/entity/CategoryType.java
  src/main/java/com/poortorich/category/entity/enums/CategoryType.java
  src/main/java/com/poortorich/category/repository/CategoryRepository.java
  src/main/java/com/poortorich/category/service/CategoryService.java
  src/main/java/com/poortorich/expense/entity/Expense.java
  src/main/java/com/poortorich/expense/entity/enums/IterationType.java
  src/main/java/com/poortorich/expense/entity/enums/PaymentMethod.java
Labels: 🛠️Refactor

#55 [#45] 지출 반복데이터 추가 기능 구현
  src/main/java/com/poortorich/PoorToRichApplication.java
  src/main/java/com/poortorich/expense/constants/ExpenseResponseMessages.java
  src/main/java/com/poortorich/expense/entity/Expense.java
  src/main/java/com/poortorich/expense/entity/enums/IterationType.java
  src/main/java/com/poortorich/expense/facade/ExpenseFacade.java
  src/main/java/com/poortorich/expense/request/ExpenseRequest.java
  src/main/java/com/poortorich/expense/response/ExpenseResponse.java
  src/main/java/com/poortorich/expense/service/ExpenseService.java
  src/main/java/com/poortorich/global/constants/DatePattern.java
  src/main/java/com/poortorich/iteration/constants/IterationResponseMessages.java
  src/main/java/com/poortorich/iteration/constants/IterationValidationConstraints.java
  src/main/java/com/poortorich/iteration/entity/IterationExpenses.java
  src/main/java/com/poortorich/iteration/entity/enums/EndType.java
  src/main/java/com/poortorich/iteration/entity/enums/IterationRuleType.java
  src/main/java/com/poortorich/iteration/entity/enums/MonthlyMode.java
  src/main/java/com/poortorich/iteration/entity/enums/Weekday.java
  src/main/java/com/poortorich/iteration/entity/info/DailyIterationRule.java
  src/main/java/com/poortorich/iteration/entity/info/IterationInfo.java
  src/main/java/com/poortorich/iteration/entity/info/MonthlyIterationRule.java
  src/main/java/com/poortorich/iteration/entity/info/WeeklyIterationRule.java
  src/main/java/com/poortorich/iteration/entity/info/YearlyIterationRule.java
  src/main/java/com/poortorich/iteration/repository/IterationExpensesRepository.java
  src/main/java/com/poortorich/iteration/repository/IterationInfoRepository.java
  src/main/java/com/poortorich/iteration/request/CustomIteration.java
  src/main/java/com/poortorich/iteration/request/End.java
  src/main/java/com/poortorich/iteration/request/IterationRule.java
  src/main/java/com/poortorich/iteration/request/MonthlyOption.java
  src/main/java/com/poortorich/iteration/response/IterationResponse.java
  src/main/java/com/poortorich/iteration/service/IterationService.java
  src/main/java/com/poortorich/iteration/util/IterationDateCalculator.java
  src/main/java/com/poortorich/iteration/validator/EndCheck.java
  src/main/java/com/poortorich/iteration/validator/EndValidator.java
  src/main/java/com/poortorich/iteration/validator/IterationRuleCheck.java
  src/main/java/com/poortorich/iteration/validator/IterationRuleValidator.java
  src/main/java/com/poortorich/iteration/validator/MonthlyOptionCheck.java
  src/main/java/com/poortorich/iteration/validator/MonthlyOptionValidator.java
  src/test/java/com/poortorich/expense/facade/ExpenseFacadeTest.java
  src/test/java/com/poortorich/expense/fixture/ExpenseFixture.java
  src/test/java/com/poortorich/expense/request/ExpenseConverterTest.java
  src/test/java/com/poortorich/expense/request/ExpenseRequestValidTest.java
  src/test/java/com/poortorich/expense/util/ExpenseRequestTestBuilder.java
  src/test/java/com/poortorich/iteration/fixture/CustomIterationFixture.java
  src/test/java/com/poortorich/iteration/fixture/EndFixture.java
  src/test/java/com/poortorich/iteration/fixture/IterationRuleFixture.java
  src/test/java/com/poortorich/iteration/fixture/MonthlyOptionFixture.java
  src/test/java/com/poortorich/iteration/fixture/enums/CycleValidationCase.java
  src/test/java/com/poortorich/iteration/fixture/enums/EndValidationCase.java
  src/test/java/com/poortorich/iteration/fixture/enums/IterationRuleValidationCase.java
  src/test/java/com/poortorich/iteration/fixture/enums/MonthlyOptionValidationCase.java
  src/test/java/com/poortorich/iteration/request/CustomIterationConverterTest.java
  src/test/java/com/poortorich/iteration/request/CustomIterationValidTest.java
  src/test/java/com/poortorich/iteration/util/CustomIterationTestBuilder.java
  src/test/java/com/poortorich/iteration/util/EndTestBuilder.java
  src/test/java/com/poortorich/iteration/util/IterationRuleTestBuilder.java
  src/test/java/com/poortorich/iteration/util/MonthlyOptionTestBuilder.java
Labels: ✨Feature, 🛠️Refactor, ✔️Test, 📬API

#69 [#68] AccessToken 전달 방식 변경
  src/main/java/com/poortorich/auth/jwt/util/JwtTokenManager.java
  src/main/java/com/poortorich/auth/service/AuthService.java
  src/main/java/com/poortorich/security/filter/auth/JwtAuthenticationFilter.java
  src/test/java/com/poortorich/auth/controller/AuthControllerTest.java
  src/test/java/com/poortorich/auth/jwt/util/JwtTokenManagerTest.java
  src/test/java/com/poortorich/auth/service/AuthServiceTest.java
  src/test/java/com/poortorich/global/config/BaseSecurityTest.java
  src/test/java/com/poortorich/security/filter/auth/JwtAuthenticationFilterTest.java
Labels: 🛠️Refactor

#74 [#73] 비밀번호 응답 메시지 수정
  src/main/java/com/poortorich/user/constants/UserResponseMessages.java
Labels: 🛠️Refactor

#71 [#70] 회원 상세 조회 API
  src/main/java/com/poortorich/user/constants/UserResponseMessages.java
  src/main/java/com/poortorich/user/controller/UserController.java
  src/main/java/com/poortorich/user/entity/enums/Gender.java
  src/main/java/com/poortorich/user/facade/UserFacade.java
  src/main/java/com/poortorich/user/response/UserDetailResponse.java
  src/main/java/com/poortorich/user/response/enums/UserResponse.java
  src/main/java/com/poortorich/user/service/UserService.java
  src/test/java/com/poortorich/user/controller/UserControllerTest.java
  src/test/java/com/poortorich/user/facade/UserFacadeTest.java
  src/test/java/com/poortorich/user/fixture/UserFixture.java
  src/test/java/com/poortorich/user/service/UserServiceTest.java
  src/test/java/com/poortorich/user/service/UserValidationServiceTest.java
  src/test/java/com/poortorich/user/util/UserRegistrationRequestTestBuilder.java
  src/test/java/com/poortorich/user/validator/UserValidatorTest.java
Labels: ✨Feature, 🛠️Refactor, ✔️Test, 📬API

#75 [#58] 카테고리 및 지출 토큰 설정
  src/main/java/com/poortorich/category/controller/CategoryController.java
  src/main/java/com/poortorich/category/entity/Category.java
  src/main/java/com/poortorich/category/repository/CategoryRepository.java
  src/main/java/com/poortorich/category/service/CategoryService.java
  src/main/java/com/poortorich/category/validator/CategoryValidator.java
  src/main/java/com/poortorich/expense/controller/ExpenseController.java
  src/main/java/com/poortorich/expense/facade/ExpenseFacade.java
  src/main/java/com/poortorich/expense/service/ExpenseService.java
  src/main/java/com/poortorich/iteration/service/IterationService.java
  src/test/java/com/poortorich/expense/controller/ExpenseControllerTest.java
  src/test/java/com/poortorich/expense/facade/ExpenseFacadeTest.java
  src/test/java/com/poortorich/expense/service/ExpenseServiceTest.java
Labels: 🛠️Refactor, ✔️Test

#78 [#72] 회원 프로필 편집 API
  src/main/java/com/poortorich/s3/constants/S3Constants.java
  src/main/java/com/poortorich/s3/service/FileUploadService.java
  src/main/java/com/poortorich/user/constants/UserResponseMessages.java
  src/main/java/com/poortorich/user/controller/UserController.java
  src/main/java/com/poortorich/user/entity/User.java
  src/main/java/com/poortorich/user/facade/UserFacade.java
  src/main/java/com/poortorich/user/request/ProfileUpdateRequest.java
  src/main/java/com/poortorich/user/response/enums/UserResponse.java
  src/main/java/com/poortorich/user/service/UserService.java
  src/main/java/com/poortorich/user/service/UserValidationService.java
  src/main/java/com/poortorich/user/validator/UserValidator.java
  src/test/java/com/poortorich/s3/constants/S3TestConfig.java
  src/test/java/com/poortorich/s3/constants/S3TestFile.java
  src/test/java/com/poortorich/s3/service/FileUploadServiceTest.java
  src/test/java/com/poortorich/s3/util/S3TestFileGenerator.java
  src/test/java/com/poortorich/user/controller/UserControllerTest.java
  src/test/java/com/poortorich/user/facade/UserFacadeTest.java
  src/test/java/com/poortorich/user/fixture/UserFixture.java
  src/test/java/com/poortorich/user/request/NicknameCheckRequestTest.java
  src/test/java/com/poortorich/user/request/ProfileUpdateRequestTest.java
  src/test/java/com/poortorich/user/request/UserRegistrationRequestTest.java
  src/test/java/com/poortorich/user/request/UsernameCheckRequestTest.java
  src/test/java/com/poortorich/user/service/UserServiceTest.java
  src/test/java/com/poortorich/user/service/UserValidationServiceTest.java
  src/test/java/com/poortorich/user/util/ProfileUpdateRequestTestBuilder.java
  src/test/java/com/poortorich/user/util/UserRegistrationRequestTestBuilder.java
  src/test/java/com/poortorich/user/validator/UserValidatorTest.java
  src/test/java/com/poortorich/user/validator/enums/BirthValidationCase.java
  src/test/java/com/poortorich/user/validator/enums/EmailValidationCase.java
  src/test/java/com/poortorich/user/validator/enums/NameValidationCase.java
  src/test/java/com/poortorich/user/validator/enums/NicknameValidationCase.java
  src/test/java/com/poortorich/user/validator/enums/PasswordValidationCase.java
  src/test/java/com/poortorich/user/validator/enums/UsernameValidationCase.java
Labels: ✨Feature, 🛠️Refactor, ✔️Test, 📬API

#79 [#77] Request 유효성 검사 응답 형식 수정
  src/main/java/com/poortorich/auth/response/enums/AuthResponse.java
  src/main/java/com/poortorich/category/response/CategoryResponse.java
  src/main/java/com/poortorich/email/response/enums/EmailResponse.java
  src/main/java/com/poortorich/expense/response/ExpenseResponse.java
  src/main/java/com/poortorich/global/exceptions/BadRequestException.java
  src/main/java/com/poortorich/global/exceptions/ConflictException.java
  src/main/java/com/poortorich/global/exceptions/NotFoundException.java
  src/main/java/com/poortorich/global/handler/GlobalExceptionHandler.java
  src/main/java/com/poortorich/global/response/BaseResponse.java
  src/main/java/com/poortorich/global/response/ExceptionResponse.java
  src/main/java/com/poortorich/global/response/Response.java
  src/main/java/com/poortorich/iteration/response/IterationResponse.java
  src/main/java/com/poortorich/s3/response/enums/S3Response.java
  src/main/java/com/poortorich/user/response/enums/UserResponse.java
  src/main/java/com/poortorich/user/validator/UserValidator.java
Labels: 🛠️Refactor

#76 [#67] 지출 가계부 조회 API 구현
  src/main/java/com/poortorich/expense/constants/ExpenseResponseMessages.java
  src/main/java/com/poortorich/expense/controller/ExpenseController.java
  src/main/java/com/poortorich/expense/entity/Expense.java
  src/main/java/com/poortorich/expense/entity/enums/IterationType.java
  src/main/java/com/poortorich/expense/entity/enums/PaymentMethod.java
  src/main/java/com/poortorich/expense/facade/ExpenseFacade.java
  src/main/java/com/poortorich/expense/repository/ExpenseRepository.java
  src/main/java/com/poortorich/expense/response/ExpenseInfoResponse.java
  src/main/java/com/poortorich/expense/response/ExpenseResponse.java
  src/main/java/com/poortorich/expense/service/ExpenseService.java
  src/main/java/com/poortorich/iteration/entity/IterationExpenses.java
  src/main/java/com/poortorich/iteration/entity/enums/EndType.java
  src/main/java/com/poortorich/iteration/entity/enums/IterationRuleType.java
  src/main/java/com/poortorich/iteration/entity/enums/MonthlyMode.java
  src/main/java/com/poortorich/iteration/entity/enums/Weekday.java
  src/main/java/com/poortorich/iteration/entity/info/IterationInfo.java
  src/main/java/com/poortorich/iteration/entity/info/WeeklyIterationRule.java
  src/main/java/com/poortorich/iteration/response/CustomIterationInfoResponse.java
  src/main/java/com/poortorich/iteration/response/EndInfoResponse.java
  src/main/java/com/poortorich/iteration/response/IterationRuleInfoResponse.java
  src/main/java/com/poortorich/iteration/response/MonthlyOptionInfoResponse.java
  src/main/java/com/poortorich/iteration/service/IterationService.java
  src/test/java/com/poortorich/expense/controller/ExpenseControllerTest.java
Labels: ✨Feature, 📬API

#82 [#80] 회원 이메일 조회 API
  src/main/java/com/poortorich/user/constants/UserResponseMessages.java
  src/main/java/com/poortorich/user/controller/UserController.java
  src/main/java/com/poortorich/user/facade/UserFacade.java
  src/main/java/com/poortorich/user/response/UserEmailResponse.java
  src/main/java/com/poortorich/user/response/enums/UserResponse.java
  src/main/java/com/poortorich/user/service/UserService.java
  src/test/java/com/poortorich/user/controller/UserControllerTest.java
  src/test/java/com/poortorich/user/facade/UserFacadeTest.java
  src/test/java/com/poortorich/user/service/UserServiceTest.java
Labels: ✨Feature, ✔️Test, 📬API

#84 [#83] 비밀번호 변경 API
  src/main/java/com/poortorich/user/constants/UserResponseMessages.java
  src/main/java/com/poortorich/user/controller/UserController.java
  src/main/java/com/poortorich/user/entity/User.java
  src/main/java/com/poortorich/user/facade/UserFacade.java
  src/main/java/com/poortorich/user/request/PasswordUpdateRequest.java
  src/main/java/com/poortorich/user/response/enums/UserResponse.java
  src/main/java/com/poortorich/user/service/UserService.java
  src/main/java/com/poortorich/user/service/UserValidationService.java
  src/main/java/com/poortorich/user/validator/UserValidator.java
  src/test/java/com/poortorich/user/controller/UserControllerTest.java
  src/test/java/com/poortorich/user/facade/UserFacadeTest.java
  src/test/java/com/poortorich/user/service/UserServiceTest.java
  src/test/java/com/poortorich/user/service/UserValidationServiceTest.java
  src/test/java/com/poortorich/user/util/PasswordUpdateRequestTestBuilder.java
  src/test/java/com/poortorich/user/validator/UserValidatorTest.java
Labels: ✨Feature, ✔️Test, 📬API

#88 [#85] 날짜 정보를 제공하는 유틸 객체 추가
  src/main/java/com/poortorich/expense/request/ExpenseRequest.java
  src/main/java/com/poortorich/global/date/constants/DateConstants.java
  src/main/java/com/poortorich/global/date/constants/DatePattern.java
  src/main/java/com/poortorich/global/date/domain/MonthInformation.java
  src/main/java/com/poortorich/global/date/domain/WeekInformation.java
  src/main/java/com/poortorich/global/date/domain/YearInformation.java
  src/main/java/com/poortorich/global/date/util/DateInfoProvider.java
  src/main/java/com/poortorich/iteration/request/End.java
  src/test/java/com/poortorich/expense/fixture/ExpenseFixture.java
  src/test/java/com/poortorich/global/date/fixture/DateTestFixture.java
  src/test/java/com/poortorich/global/date/util/DateInfoProviderTest.java
Labels: ✨Feature, ✔️Test

#90 [#89] CORS 설정 추가
  src/main/java/com/poortorich/security/constants/SecurityConstants.java
Labels: 🌏Deploy, ⚙️Setting

#93 [#92] response 필드 이름 수정
  src/main/java/com/poortorich/global/response/BaseResponse.java
  src/main/java/com/poortorich/global/response/DataResponse.java
Labels: 🛠️Refactor

#95 [#94] 응답 필드 수정에 영향을 받는 로직 수정
  src/main/java/com/poortorich/security/filter/auth/JwtAuthenticationFilter.java
  src/test/java/com/poortorich/auth/controller/AuthControllerTest.java
  src/test/java/com/poortorich/expense/controller/ExpenseControllerTest.java
  src/test/java/com/poortorich/security/filter/auth/JwtAuthenticationFilterTest.java
  src/test/java/com/poortorich/user/controller/UserControllerTest.java
  src/test/java/com/poortorich/user/validator/UserValidatorTest.java
Labels: 🛠️Refactor

#97 [#96] 카테고리 활성화/비활성화 API 구현
  src/main/java/com/poortorich/category/constants/CategoryResponseMessage.java
  src/main/java/com/poortorich/category/controller/CategoryController.java
  src/main/java/com/poortorich/category/entity/Category.java
  src/main/java/com/poortorich/category/request/CategoryVisibilityRequest.java
  src/main/java/com/poortorich/category/response/CategoryResponse.java
  src/main/java/com/poortorich/category/service/CategoryService.java
Labels: ✨Feature, 🛠️Refactor, 📬API

#98 [#91] 통계 계산 유틸 객체 추가
  src/main/java/com/poortorich/global/statistics/util/StatCalculator.java
  src/test/java/com/poortorich/global/statistics/fixture/StatCalculatorTestFixture.java
  src/test/java/com/poortorich/global/statistics/util/StatCalculatorTest.java
Labels: ✨Feature, ✔️Test

#87 [#86] 지출 가계부 삭제 API 구현
  src/main/java/com/poortorich/category/service/CategoryService.java
  src/main/java/com/poortorich/expense/constants/ExpenseResponseMessages.java
  src/main/java/com/poortorich/expense/controller/ExpenseController.java
  src/main/java/com/poortorich/expense/facade/ExpenseFacade.java
  src/main/java/com/poortorich/expense/request/ExpenseDeleteRequest.java
  src/main/java/com/poortorich/expense/request/enums/IterationAction.java
  src/main/java/com/poortorich/expense/response/ExpenseResponse.java
  src/main/java/com/poortorich/expense/service/ExpenseService.java
  src/main/java/com/poortorich/iteration/entity/IterationExpenses.java
  src/main/java/com/poortorich/iteration/repository/IterationExpensesRepository.java
  src/main/java/com/poortorich/iteration/service/IterationService.java
  src/main/java/com/poortorich/user/service/UserService.java
  src/test/java/com/poortorich/expense/facade/ExpenseFacadeTest.java
  src/test/java/com/poortorich/expense/service/ExpenseServiceTest.java
Labels: ✨Feature, 🛠️Refactor, 📬API

#102 [#101] 기본 카테고리 추가 기능 추가
  src/main/java/com/poortorich/category/domain/model/enums/DefaultExpenseCategory.java
  src/main/java/com/poortorich/category/domain/model/enums/DefaultIncomeCategory.java
  src/main/java/com/poortorich/category/repository/CategoryRepository.java
  src/main/java/com/poortorich/category/service/CategoryService.java
  src/main/java/com/poortorich/expense/entity/Expense.java
  src/main/java/com/poortorich/expense/facade/ExpenseFacade.java
  src/main/java/com/poortorich/expense/service/ExpenseService.java
  src/main/java/com/poortorich/user/facade/UserFacade.java
  src/main/java/com/poortorich/user/service/UserService.java
  src/test/java/com/poortorich/expense/facade/ExpenseFacadeTest.java
  src/test/java/com/poortorich/expense/service/ExpenseServiceTest.java
Labels: ✨Feature, 📬API

#104 [#103] 회원가입 시 기본 프로필 적용
  src/main/java/com/poortorich/s3/service/FileUploadService.java
  src/main/java/com/poortorich/user/request/UserRegistrationRequest.java
Labels: 📬API

#106 [#81] 지출 편집 API
  src/main/java/com/poortorich/expense/constants/ExpenseResponseMessages.java
  src/main/java/com/poortorich/expense/controller/ExpenseController.java
  src/main/java/com/poortorich/expense/entity/Expense.java
  src/main/java/com/poortorich/expense/facade/ExpenseFacade.java
  src/main/java/com/poortorich/expense/request/ExpenseRequest.java
  src/main/java/com/poortorich/expense/response/ExpenseResponse.java
  src/main/java/com/poortorich/expense/service/ExpenseService.java
  src/main/java/com/poortorich/iteration/constants/IterationResponseMessages.java
  src/main/java/com/poortorich/iteration/response/IterationResponse.java
  src/main/java/com/poortorich/iteration/service/IterationService.java
  src/test/java/com/poortorich/expense/util/ExpenseRequestTestBuilder.java
Labels: ✨Feature, 🛠️Refactor, 📬API

#108 [#105] 지출 총액 및 저축 총액 조회 API
  src/main/java/com/poortorich/category/domain/model/enums/DefaultExpenseCategory.java
  src/main/java/com/poortorich/chart/constants/ChartConstants.java
  src/main/java/com/poortorich/chart/constants/ChartResponseMessage.java
  src/main/java/com/poortorich/chart/controller/ChartController.java
  src/main/java/com/poortorich/chart/facade/ChartFacade.java
  src/main/java/com/poortorich/chart/response/ChartResponse.java
  src/main/java/com/poortorich/chart/response/TotalAmountAndSavingResponse.java
  src/main/java/com/poortorich/chart/service/ChartService.java
  src/main/java/com/poortorich/expense/repository/ExpenseRepository.java
  src/main/java/com/poortorich/expense/request/ExpenseRequest.java
  src/main/java/com/poortorich/expense/service/ExpenseService.java
  src/main/java/com/poortorich/expense/util/ExpenseCostExtractor.java
  src/main/java/com/poortorich/global/date/constants/DatePattern.java
  src/main/java/com/poortorich/global/date/domain/DateInfo.java
  src/main/java/com/poortorich/global/date/domain/MonthInformation.java
  src/main/java/com/poortorich/global/date/domain/WeekInformation.java
  src/main/java/com/poortorich/global/date/domain/YearInformation.java
  src/main/java/com/poortorich/global/date/response/enums/DateResponse.java
  src/main/java/com/poortorich/global/date/util/DateInfoProvider.java
  src/main/java/com/poortorich/iteration/request/End.java
  src/test/java/com/poortorich/category/entity/CategoryFixture.java
  src/test/java/com/poortorich/chart/controller/ChartControllerTest.java
  src/test/java/com/poortorich/chart/facade/ChartFacadeTest.java
  src/test/java/com/poortorich/chart/service/ChartServiceTest.java
  src/test/java/com/poortorich/expense/fixture/ExpenseFixture.java
  src/test/java/com/poortorich/expense/util/ExpenseCostExtractorTest.java
  src/test/java/com/poortorich/global/date/fixture/DateTestFixture.java
  src/test/java/com/poortorich/global/date/util/DateInfoProviderTest.java
  src/test/java/com/poortorich/user/facade/UserFacadeTest.java
Labels: ✨Feature, ✔️Test, 📬API
