Repository Poor-To-Rich/backend, pull requests merged in 2025-08, with the labels that each got.

#339 [#333] 내가 방장인 채팅방 목록 조회 API 구현
  src/main/java/com/poortorich/chat/constants/ChatResponseMessage.java
  src/main/java/com/poortorich/chat/controller/ChatParticipantController.java
  src/main/java/com/poortorich/chat/facade/ChatFacade.java
  src/main/java/com/poortorich/chat/repository/ChatMessageRepository.java
  src/main/java/com/poortorich/chat/repository/ChatParticipantRepository.java
  src/main/java/com/poortorich/chat/repository/ChatroomRepository.java
  src/main/java/com/poortorich/chat/response/ChatroomResponse.java
  src/main/java/com/poortorich/chat/response/ChatroomsResponse.java
  src/main/java/com/poortorich/chat/response/enums/ChatResponse.java
  src/main/java/com/poortorich/chat/service/ChatMessageService.java
  src/main/java/com/poortorich/chat/service/ChatParticipantService.java
  src/main/java/com/poortorich/chat/service/ChatroomService.java
  src/main/java/com/poortorich/chat/util/ChatBuilder.java
  src/main/java/com/poortorich/chat/validator/ChatroomValidator.java
  src/test/java/com/poortorich/chat/controller/ChatParticipantControllerTest.java
  src/test/java/com/poortorich/chat/facade/ChatFacadeTest.java
  src/test/java/com/poortorich/chat/service/ChatMessageServiceTest.java
  src/test/java/com/poortorich/chat/service/ChatParticipantServiceTest.java
  src/test/java/com/poortorich/chat/service/ChatroomServiceTest.java
Labels: ✨Feature, 📬API

#340 [#338] 채팅방 편집/조회 필드 추가
  build.gradle
  src/main/java/com/poortorich/chat/constants/ChatResponseMessage.java
  src/main/java/com/poortorich/chat/facade/ChatFacade.java
  src/main/java/com/poortorich/chat/request/ChatroomUpdateRequest.java
  src/main/java/com/poortorich/chat/response/ChatroomInfoResponse.java
  src/main/java/com/poortorich/chat/util/ChatBuilder.java
Labels: ✨Feature, 📬API

#347 [#344] 채팅방 검색 목록 API 구현
  src/main/java/com/poortorich/chat/constants/ChatResponseMessage.java
  src/main/java/com/poortorich/chat/controller/ChatController.java
  src/main/java/com/poortorich/chat/facade/ChatFacade.java
  src/main/java/com/poortorich/chat/repository/ChatroomRepository.java
  src/main/java/com/poortorich/chat/response/enums/ChatResponse.java
  src/main/java/com/poortorich/chat/service/ChatroomService.java
  src/test/java/com/poortorich/chat/controller/ChatControllerTest.java
  src/test/java/com/poortorich/chat/facade/ChatFacadeTest.java
  src/test/java/com/poortorich/chat/service/ChatroomServiceTest.java
Labels: ✨Feature, 📬API

#354 [#353] 채팅방 정보 조회 API 구현
  src/main/java/com/poortorich/chat/constants/ChatResponseMessage.java
  src/main/java/com/poortorich/chat/controller/ChatController.java
  src/main/java/com/poortorich/chat/entity/ChatMessage.java
  src/main/java/com/poortorich/chat/entity/Chatroom.java
  src/main/java/com/poortorich/chat/facade/ChatFacade.java
  src/main/java/com/poortorich/chat/response/ChatroomDetailsResponse.java
  src/main/java/com/poortorich/chat/response/enums/ChatResponse.java
  src/main/java/com/poortorich/chat/util/ChatBuilder.java
  src/test/java/com/poortorich/chat/controller/ChatControllerTest.java
  src/test/java/com/poortorich/chat/facade/ChatFacadeTest.java
Labels: ✨Feature, 📬API

#356 [#355] 채팅방 태그 제한 수정
  src/main/java/com/poortorich/chat/constants/ChatResponseMessage.java
  src/main/java/com/poortorich/chat/constants/ChatValidationConstraints.java
  src/main/java/com/poortorich/chat/repository/ChatParticipantRepository.java
  src/main/java/com/poortorich/chat/request/ChatroomCreateRequest.java
  src/main/java/com/poortorich/chat/service/ChatParticipantService.java
  src/main/java/com/poortorich/tag/constants/TagResponseMessage.java
  src/main/java/com/poortorich/tag/constants/TagValidationConstraints.java
  src/main/java/com/poortorich/tag/response/enums/TagResponse.java
  src/main/java/com/poortorich/tag/service/TagService.java
  src/test/java/com/poortorich/tag/service/TagServiceTest.java
Labels: 🛠️Refactor

#349 [#346] 채팅 메시지 발행
  src/main/java/com/poortorich/chat/constants/ChatResponseMessage.java
  src/main/java/com/poortorich/chat/controller/ChatController.java
  src/main/java/com/poortorich/chat/manager/ChatroomLeaveManager.java
  src/main/java/com/poortorich/chat/realtime/builder/UserChatMessageBuilder.java
  src/main/java/com/poortorich/chat/realtime/controller/ChatRealtimeController.java
  src/main/java/com/poortorich/chat/realtime/facade/ChatRealTimeFacade.java
  src/main/java/com/poortorich/chat/realtime/payload/interfaces/ResponsePayload.java
  src/main/java/com/poortorich/chat/realtime/payload/request/ChatMessageRequestPayload.java
  src/main/java/com/poortorich/chat/realtime/payload/response/BasePayload.java
  src/main/java/com/poortorich/chat/realtime/payload/response/ChatroomClosedResponsePayload.java
  src/main/java/com/poortorich/chat/realtime/payload/response/UserChatMessagePayload.java
  src/main/java/com/poortorich/chat/realtime/payload/response/UserEnterResponsePayload.java
  src/main/java/com/poortorich/chat/realtime/payload/response/UserLeaveResponsePayload.java
  src/main/java/com/poortorich/chat/repository/ChatParticipantRepository.java
  src/main/java/com/poortorich/chat/repository/UnreadChatMessageRepository.java
  src/main/java/com/poortorich/chat/service/ChatMessageService.java
  src/main/java/com/poortorich/chat/service/ChatParticipantService.java
  src/main/java/com/poortorich/chat/service/UnreadChatMessageService.java
  src/main/java/com/poortorich/websocket/stomp/command/publish/handler/StompSendHandler.java
  src/main/java/com/poortorich/websocket/stomp/command/publish/validator/StompPublishValidator.java
Labels: ✨Feature, 📬API, 🛜WebSocket

#363 [#362] 채팅방 편집 DTO 검증 로직 추가
  src/main/java/com/poortorich/chat/request/ChatroomUpdateRequest.java
Labels: ✨Feature

#368 [#365] 랭킹 기능 활성화 메시지 생성 로직
  src/main/java/com/poortorich/chat/constants/ChatResponseMessage.java
  src/main/java/com/poortorich/chat/controller/ChatController.java
  src/main/java/com/poortorich/chat/facade/ChatFacade.java
  src/main/java/com/poortorich/chat/realtime/builder/RankingStatusChatMessageBuilder.java
  src/main/java/com/poortorich/chat/realtime/collect/ChatPayloadCollector.java
  src/main/java/com/poortorich/chat/realtime/facade/ChatRealTimeFacade.java
  src/main/java/com/poortorich/chat/realtime/payload/request/ChatMessageRequestPayload.java
  src/main/java/com/poortorich/chat/realtime/payload/response/RankingStatusMessagePayload.java
  src/main/java/com/poortorich/chat/response/ChatroomUpdateResponse.java
  src/main/java/com/poortorich/chat/service/ChatMessageService.java
  src/main/java/com/poortorich/chat/util/detector/RankingStatusChangeDetector.java
Labels: ✨Feature, 📬API, 🛜WebSocket

#372 [#371] 좋아요 도메인 리팩토링
  src/main/java/com/poortorich/chat/constants/ChatResponseMessage.java
  src/main/java/com/poortorich/chat/controller/ChatController.java
  src/main/java/com/poortorich/chat/facade/ChatFacade.java
  src/main/java/com/poortorich/chat/request/ChatroomLikeUpdateRequest.java
  src/main/java/com/poortorich/chat/response/enums/ChatResponse.java
  src/main/java/com/poortorich/like/constants/LikeResponseMessage.java
  src/main/java/com/poortorich/like/controller/LikeController.java
  src/main/java/com/poortorich/like/facade/LikeFacade.java
  src/main/java/com/poortorich/like/request/LikeUpdateRequest.java
  src/main/java/com/poortorich/like/response/LikeStatusResponse.java
  src/main/java/com/poortorich/like/response/enums/LikeResponse.java
  src/test/java/com/poortorich/chat/controller/ChatControllerTest.java
  src/test/java/com/poortorich/chat/facade/ChatFacadeTest.java
  src/test/java/com/poortorich/like/controller/LikeControllerTest.java
  src/test/java/com/poortorich/like/facade/LikeFacadeTest.java
Labels: 🛠️Refactor

#376 [#375] 이전 채팅 조회 API 커서 수정
  src/main/java/com/poortorich/chat/repository/ChatMessageRepository.java
  src/main/java/com/poortorich/chat/service/ChatMessageService.java
Labels: 🐞BugFix

#390 [#389] 토큰 재발급 액세스 토큰 제공 오류 수정
  src/main/java/com/poortorich/auth/service/AuthService.java
  src/test/java/com/poortorich/chat/facade/ChatFacadeTest.java
Labels: 🐞BugFix

#393 [#392] 누락된 페이로드 필드 추가
  src/main/java/com/poortorich/chat/util/mapper/ChatMessageMapper.java
Labels: 🐞BugFix

#396 [#395] 최근 공지 조회 API 수정
  src/main/java/com/poortorich/chatnotice/facade/ChatNoticeFacade.java
  src/main/java/com/poortorich/chatnotice/service/ChatNoticeService.java
  src/test/java/com/poortorich/chatnotice/facade/ChatNoticeFacadeTest.java
  src/test/java/com/poortorich/chatnotice/service/ChatNoticeServiceTest.java
Labels: 🛠️Refactor

#404 [#403] 누락된 필드 및 오타 수정
  src/main/java/com/poortorich/chat/realtime/payload/response/ChatroomClosedResponsePayload.java
  src/main/java/com/poortorich/chat/realtime/payload/response/RankingStatusMessagePayload.java
  src/main/java/com/poortorich/chat/realtime/payload/response/UserChatMessagePayload.java
  src/main/java/com/poortorich/chat/realtime/payload/response/UserEnterResponsePayload.java
  src/main/java/com/poortorich/chat/realtime/payload/response/UserLeaveResponsePayload.java
  src/main/java/com/poortorich/chat/service/ChatMessageService.java
  src/main/java/com/poortorich/chat/util/mapper/ChatMessageMapper.java
Labels: 🐞BugFix, 🛠️Refactor

#408 [#407] 채팅방 편집 누락된 필드 추가
  src/main/java/com/poortorich/chat/entity/Chatroom.java
Labels: 🐞BugFix

#413 [#412] 이전 채팅 조회 오류 수정
  src/main/java/com/poortorich/chat/realtime/event/user/UserProfileUpdatedEventListener.java
  src/main/java/com/poortorich/chat/realtime/payload/response/RankingStatusMessagePayload.java
  src/main/java/com/poortorich/chat/realtime/payload/response/UserUpdatedResponsePayload.java
  src/main/java/com/poortorich/chat/util/mapper/ChatMessageMapper.java
Labels: 🐞BugFix

#409 [#402] 날짜 메시지 브로드캐스트
  src/main/java/com/poortorich/chat/controller/ChatController.java
  src/main/java/com/poortorich/chat/entity/enums/MessageType.java
  src/main/java/com/poortorich/chat/realtime/builder/SystemMessageBuilder.java
  src/main/java/com/poortorich/chat/realtime/event/datechange/DateChangeEvent.java
  src/main/java/com/poortorich/chat/realtime/event/datechange/DateChangeEventListner.java
  src/main/java/com/poortorich/chat/realtime/event/datechange/detector/DateChangeDetector.java
  src/main/java/com/poortorich/chat/realtime/facade/ChatRealTimeFacade.java
  src/main/java/com/poortorich/chat/realtime/payload/response/DateChangeMessagePayload.java
  src/main/java/com/poortorich/chat/repository/ChatMessageRepository.java
  src/main/java/com/poortorich/chat/repository/ChatParticipantRepository.java
  src/main/java/com/poortorich/chat/service/ChatMessageService.java
  src/main/java/com/poortorich/chat/util/mapper/ChatMessageMapper.java
Labels: ✨Feature, 📬API, 🛜WebSocket

#422 [#416] 채팅방 입장 api 직렬화 오류 수정
  src/main/java/com/poortorich/chat/request/ChatroomEnterRequest.java
  src/main/java/com/poortorich/chat/validator/ChatroomValidator.java
Labels: 🐞BugFix, 📬API

#429 [#428] 실시간 읽음 처리 로직 수정
  src/main/java/com/poortorich/websocket/stomp/command/subscribe/handler/StompSubscribeHandler.java
  src/main/java/com/poortorich/websocket/stomp/command/unsubscribe/handler/StompUnsubscribeHandler.java
  src/main/java/com/poortorich/websocket/stomp/service/SubscribeService.java
Labels: 🐞BugFix, 🛜WebSocket

#421 [#420] 공지 상세 조회 API 구현
  src/main/java/com/poortorich/chat/util/ChatBuilder.java
  src/main/java/com/poortorich/chatnotice/constants/ChatNoticeResponseMessage.java
  src/main/java/com/poortorich/chatnotice/controller/ChatNoticeController.java
  src/main/java/com/poortorich/chatnotice/entity/ChatNotice.java
  src/main/java/com/poortorich/chatnotice/facade/ChatNoticeFacade.java
  src/main/java/com/poortorich/chatnotice/repository/ChatNoticeRepository.java
  src/main/java/com/poortorich/chatnotice/response/NoticeDetailsResponse.java
  src/main/java/com/poortorich/chatnotice/response/enums/ChatNoticeResponse.java
  src/main/java/com/poortorich/chatnotice/service/ChatNoticeService.java
  src/main/java/com/poortorich/chatnotice/util/ChatNoticeBuilder.java
  src/test/java/com/poortorich/chatnotice/controller/ChatNoticeControllerTest.java
  src/test/java/com/poortorich/chatnotice/facade/ChatNoticeFacadeTest.java
  src/test/java/com/poortorich/chatnotice/service/ChatNoticeServiceTest.java
Labels: ✨Feature, 📬API

#424 [#423] 채팅방 공지 추가/수정/삭제 발행
  src/main/java/com/poortorich/chat/realtime/controller/ChatRealtimeController.java
  src/main/java/com/poortorich/chat/realtime/facade/ChatRealTimeFacade.java
  src/main/java/com/poortorich/chat/realtime/payload/request/ChatNoticeRequestPayload.java
  src/main/java/com/poortorich/chat/realtime/payload/request/enums/NoticeType.java
  src/main/java/com/poortorich/chat/realtime/payload/response/enums/PayloadType.java
  src/main/java/com/poortorich/chat/service/ChatParticipantService.java
  src/main/java/com/poortorich/chat/validator/ChatParticipantValidator.java
  src/main/java/com/poortorich/chatnotice/constants/ChatNoticeResponseMessage.java
  src/main/java/com/poortorich/chatnotice/entity/ChatNotice.java
  src/main/java/com/poortorich/chatnotice/response/enums/ChatNoticeResponse.java
  src/main/java/com/poortorich/chatnotice/service/ChatNoticeService.java
  src/main/java/com/poortorich/websocket/stomp/command/publish/endpoint/PublishEndpoint.java
Labels: ✨Feature, 🛜WebSocket

#439 [#438] Github Actions 파일 수정
  .github/workflows/main.yml
Labels: ⚙️Setting

#436 [#427] 전체 공지 목록 조회 API 구현
  src/main/java/com/poortorich/chatnotice/constants/ChatNoticeResponseMessage.java
  src/main/java/com/poortorich/chatnotice/controller/ChatNoticeController.java
  src/main/java/com/poortorich/chatnotice/facade/ChatNoticeFacade.java
  src/main/java/com/poortorich/chatnotice/repository/ChatNoticeRepository.java
  src/main/java/com/poortorich/chatnotice/response/AllNoticesResponse.java
  src/main/java/com/poortorich/chatnotice/response/NoticeResponse.java
  src/main/java/com/poortorich/chatnotice/response/enums/ChatNoticeResponse.java
  src/main/java/com/poortorich/chatnotice/service/ChatNoticeService.java
  src/main/java/com/poortorich/chatnotice/util/ChatNoticeBuilder.java
  src/test/java/com/poortorich/chatnotice/controller/ChatNoticeControllerTest.java
  src/test/java/com/poortorich/chatnotice/facade/ChatNoticeFacadeTest.java
  src/test/java/com/poortorich/chatnotice/service/ChatNoticeServiceTest.java
Labels: ✨Feature, 📬API

#445 [#442] 최신 랭킹 조회 API 구현
  src/main/java/com/poortorich/ranking/constants/RankingResponseMessage.java
  src/main/java/com/poortorich/ranking/controller/RankingController.java
  src/main/java/com/poortorich/ranking/facade/RankingFacade.java
  src/main/java/com/poortorich/ranking/repository/RankingRepository.java
  src/main/java/com/poortorich/ranking/response/LatestRankingResponse.java
  src/main/java/com/poortorich/ranking/response/enums/RankingResponse.java
  src/main/java/com/poortorich/ranking/service/RankingService.java
  src/main/java/com/poortorich/ranking/util/RankingBuilder.java
  src/test/java/com/poortorich/ranking/controller/RankingControllerTest.java
  src/test/java/com/poortorich/ranking/facade/RankingFacadeTest.java
  src/test/java/com/poortorich/ranking/service/RankingServiceTest.java
Labels: ✨Feature, 📬API

#441 [#437] 전체 참여 인원 목록 조회 API 구현
  src/main/java/com/poortorich/chat/constants/ChatResponseMessage.java
  src/main/java/com/poortorich/chat/controller/ChatParticipantController.java
  src/main/java/com/poortorich/chat/facade/ChatFacade.java
  src/main/java/com/poortorich/chat/repository/ChatParticipantRepository.java
  src/main/java/com/poortorich/chat/response/AllParticipantsResponse.java
  src/main/java/com/poortorich/chat/response/enums/ChatResponse.java
  src/main/java/com/poortorich/chat/service/ChatParticipantService.java
  src/main/java/com/poortorich/chat/util/ChatBuilder.java
  src/test/java/com/poortorich/chat/controller/ChatParticipantControllerTest.java
  src/test/java/com/poortorich/chat/facade/ChatFacadeTest.java
  src/test/java/com/poortorich/chat/service/ChatParticipantServiceTest.java
Labels: ✨Feature, 📬API

#454 [#446] 최신 사진 목록 조회 API 구현
  src/main/java/com/poortorich/photo/constants/PhotoResponseMessage.java
  src/main/java/com/poortorich/photo/controller/PhotoController.java
  src/main/java/com/poortorich/photo/facade/PhotoFacade.java
  src/main/java/com/poortorich/photo/repository/PhotoRepository.java
  src/main/java/com/poortorich/photo/response/PhotoInfoResponse.java
  src/main/java/com/poortorich/photo/response/PreviewPhotosResponse.java
  src/main/java/com/poortorich/photo/response/enums/PhotoResponse.java
  src/main/java/com/poortorich/photo/service/PhotoService.java
  src/main/java/com/poortorich/photo/util/PhotoBuilder.java
  src/test/java/com/poortorich/photo/controller/PhotoControllerTest.java
  src/test/java/com/poortorich/photo/facade/PhotoFacadeTest.java
  src/test/java/com/poortorich/photo/service/PhotoServiceTest.java
Labels: ✨Feature, 📬API

#460 [#457] 사용자 강제퇴장 API
  src/main/java/com/poortorich/chat/constants/ChatResponseMessage.java
  src/main/java/com/poortorich/chat/controller/ChatController.java
  src/main/java/com/poortorich/chat/entity/ChatParticipant.java
  src/main/java/com/poortorich/chat/facade/ChatFacade.java
  src/main/java/com/poortorich/chat/realtime/builder/SystemMessageBuilder.java
  src/main/java/com/poortorich/chat/realtime/facade/ChatRealTimeFacade.java
  src/main/java/com/poortorich/chat/realtime/payload/response/KickChatParticipantMessagePayload.java
  src/main/java/com/poortorich/chat/response/KickChatParticipantResponse.java
  src/main/java/com/poortorich/chat/response/enums/ChatResponse.java
  src/main/java/com/poortorich/chat/service/ChatMessageService.java
  src/main/java/com/poortorich/chat/service/ChatParticipantService.java
  src/main/java/com/poortorich/tag/service/TagService.java
Labels: ✨Feature, 📬API, 🛜WebSocket

#464 [#462] 실시간 읽음 처리 로직 수정
  src/main/java/com/poortorich/websocket/stomp/command/disconnect/handler/StompDisconnectHandler.java
  src/main/java/com/poortorich/websocket/stomp/interceptor/StompInterceptor.java
  src/main/java/com/poortorich/websocket/stomp/service/SubscribeService.java
Labels: 🐞BugFix, 🛜WebSocket

#475 [#474] 참여중인 채팅방 목록 조회 API
  src/main/java/com/poortorich/chat/constants/ChatResponseMessage.java
  src/main/java/com/poortorich/chat/controller/UserChatroomController.java
  src/main/java/com/poortorich/chat/facade/ChatFacade.java
  src/main/java/com/poortorich/chat/model/ChatroomPaginationContext.java
  src/main/java/com/poortorich/chat/repository/ChatMessageRepository.java
  src/main/java/com/poortorich/chat/repository/ChatParticipantRepository.java
  src/main/java/com/poortorich/chat/repository/ChatroomRepository.java
  src/main/java/com/poortorich/chat/repository/UnreadChatMessageRepository.java
  src/main/java/com/poortorich/chat/response/MyChatroom.java
  src/main/java/com/poortorich/chat/response/MyChatroomsResponse.java
  src/main/java/com/poortorich/chat/response/enums/ChatResponse.java
  src/main/java/com/poortorich/chat/service/ChatMessageService.java
  src/main/java/com/poortorich/chat/service/ChatParticipantService.java
  src/main/java/com/poortorich/chat/service/ChatroomService.java
  src/main/java/com/poortorich/chat/service/UnreadChatMessageService.java
  src/main/java/com/poortorich/chat/util/mapper/ChatMessageContentMapper.java
  src/main/java/com/poortorich/chat/util/mapper/ChatroomMapper.java
  src/main/java/com/poortorich/chat/util/provider/ChatPaginationProvider.java
Labels: ✨Feature, 📬API

#484 [#483] 웹소켓 오류 수정
  src/main/java/com/poortorich/websocket/config/WebSocketConfig.java
  src/main/java/com/poortorich/websocket/stomp/command/unsubscribe/handler/StompUnsubscribeHandler.java
Labels: 🐞BugFix, 🛜WebSocket

#482 [#481] 사용자 프로필 조회 API userId 필드 추가
  src/main/java/com/poortorich/user/response/UserDetailResponse.java
  src/main/java/com/poortorich/user/service/UserService.java
Labels: ✨Feature, 🛠️Refactor

#478 [#477] 참여중인 채팅방 목록 구독
  src/main/java/com/poortorich/chat/constants/ChatResponseMessage.java
  src/main/java/com/poortorich/chat/facade/ChatFacade.java
  src/main/java/com/poortorich/chat/realtime/event/chatroom/ChatroomUpdateEvent.java
  src/main/java/com/poortorich/chat/realtime/event/chatroom/ChatroomUpdateEventListener.java
  src/main/java/com/poortorich/chat/realtime/event/chatroom/ParticipantUpdateEvent.java
  src/main/java/com/poortorich/chat/realtime/event/chatroom/UserChatroomUpdateEvent.java
  src/main/java/com/poortorich/chat/realtime/event/chatroom/detector/ChatroomUpdateDetector.java
  src/main/java/com/poortorich/chat/realtime/facade/ChatRealTimeFacade.java
  src/main/java/com/poortorich/chat/realtime/payload/response/enums/PayloadType.java
  src/main/java/com/poortorich/chat/repository/UnreadChatMessageRepository.java
  src/main/java/com/poortorich/chat/response/enums/ChatResponse.java
  src/main/java/com/poortorich/chat/util/mapper/ChatMessageContentMapper.java
  src/main/java/com/poortorich/websocket/stomp/command/subscribe/endpoint/SubscribeEndpoint.java
  src/main/java/com/poortorich/websocket/stomp/command/subscribe/handler/StompSubscribeHandler.java
  src/main/java/com/poortorich/websocket/stomp/command/subscribe/util/SubscribeEndpointExtractor.java
  src/main/java/com/poortorich/websocket/stomp/command/subscribe/validator/SubscribeValidator.java
Labels: ✨Feature, 🛜WebSocket

#488 [#487] 백엔드 서버 배포
  src/main/java/com/poortorich/chat/constants/ChatResponseMessage.java
  src/main/java/com/poortorich/chat/controller/UserChatroomController.java
  src/main/java/com/poortorich/chat/entity/ChatParticipant.java
  src/main/java/com/poortorich/chat/entity/Chatroom.java
  src/main/java/com/poortorich/chat/facade/ChatFacade.java
  src/main/java/com/poortorich/chat/model/ChatroomPaginationContext.java
  src/main/java/com/poortorich/chat/realtime/builder/UserChatMessageBuilder.java
  src/main/java/com/poortorich/chat/realtime/event/chatroom/ChatroomUpdateEvent.java
  src/main/java/com/poortorich/chat/realtime/event/chatroom/ChatroomUpdateEventListener.java
  src/main/java/com/poortorich/chat/realtime/event/chatroom/ParticipantUpdateEvent.java
  src/main/java/com/poortorich/chat/realtime/event/chatroom/UserChatroomUpdateEvent.java
  src/main/java/com/poortorich/chat/realtime/event/chatroom/detector/ChatroomUpdateDetector.java
  src/main/java/com/poortorich/chat/realtime/facade/ChatRealTimeFacade.java
  src/main/java/com/poortorich/chat/realtime/payload/response/UserChatMessagePayload.java
  src/main/java/com/poortorich/chat/realtime/payload/response/enums/PayloadType.java
  src/main/java/com/poortorich/chat/repository/ChatMessageRepository.java
  src/main/java/com/poortorich/chat/repository/ChatParticipantRepository.java
  src/main/java/com/poortorich/chat/repository/ChatroomRepository.java
  src/main/java/com/poortorich/chat/repository/UnreadChatMessageRepository.java
  src/main/java/com/poortorich/chat/response/MyChatroom.java
  src/main/java/com/poortorich/chat/response/MyChatroomsResponse.java
  src/main/java/com/poortorich/chat/response/enums/ChatResponse.java
  src/main/java/com/poortorich/chat/service/ChatMessageService.java
  src/main/java/com/poortorich/chat/service/ChatParticipantService.java
  src/main/java/com/poortorich/chat/service/ChatroomService.java
  src/main/java/com/poortorich/chat/service/UnreadChatMessageService.java
  src/main/java/com/poortorich/chat/util/ChatBuilder.java
  src/main/java/com/poortorich/chat/util/manager/ChatroomLeaveManager.java
  src/main/java/com/poortorich/chat/util/mapper/ChatMessageContentMapper.java
  src/main/java/com/poortorich/chat/util/mapper/ChatMessageMapper.java
  src/main/java/com/poortorich/chat/util/mapper/ChatroomMapper.java
  src/main/java/com/poortorich/chat/util/provider/ChatPaginationProvider.java
  src/main/java/com/poortorich/chat/validator/ChatroomValidator.java
  src/main/java/com/poortorich/global/date/constants/DatePattern.java
  src/main/java/com/poortorich/global/date/util/DateParser.java
  src/main/java/com/poortorich/photo/constants/PhotoResponseMessage.java
  src/main/java/com/poortorich/photo/controller/PhotoController.java
  src/main/java/com/poortorich/photo/facade/PhotoFacade.java
  src/main/java/com/poortorich/photo/repository/PhotoRepository.java
  src/main/java/com/poortorich/photo/response/AllPhotosResponse.java
  src/main/java/com/poortorich/photo/response/PhotoCursorResponse.java
  src/main/java/com/poortorich/photo/response/PhotoInfoResponse.java
  src/main/java/com/poortorich/photo/response/enums/PhotoResponse.java
  src/main/java/com/poortorich/photo/service/PhotoService.java
  src/main/java/com/poortorich/photo/util/PhotoBuilder.java
  src/main/java/com/poortorich/user/response/UserDetailResponse.java
  src/main/java/com/poortorich/user/service/UserService.java
  src/main/java/com/poortorich/websocket/config/WebSocketConfig.java
  src/main/java/com/poortorich/websocket/stomp/command/subscribe/endpoint/SubscribeEndpoint.java
  src/main/java/com/poortorich/websocket/stomp/command/subscribe/handler/StompSubscribeHandler.java
  src/main/java/com/poortorich/websocket/stomp/command/subscribe/util/SubscribeEndpointExtractor.java
  src/main/java/com/poortorich/websocket/stomp/command/subscribe/validator/SubscribeValidator.java
  src/main/java/com/poortorich/websocket/stomp/command/unsubscribe/handler/StompUnsubscribeHandler.java
  src/test/java/com/poortorich/chat/facade/ChatFacadeTest.java
  src/test/java/com/poortorich/photo/controller/PhotoControllerTest.java
  src/test/java/com/poortorich/photo/facade/PhotoFacadeTest.java
  src/test/java/com/poortorich/photo/service/PhotoServiceTest.java
Labels: 🌏Deploy

#493 [#485] 전체 랭킹 목록 조회 API 구현
  src/main/java/com/poortorich/chat/repository/ChatParticipantRepository.java
  src/main/java/com/poortorich/chat/service/ChatParticipantService.java
  src/main/java/com/poortorich/chat/util/ChatBuilder.java
  src/main/java/com/poortorich/ranking/constants/RankingResponseMessage.java
  src/main/java/com/poortorich/ranking/controller/RankingController.java
  src/main/java/com/poortorich/ranking/entity/Ranking.java
  src/main/java/com/poortorich/ranking/facade/RankingFacade.java
  src/main/java/com/poortorich/ranking/repository/RankingRepository.java
  src/main/java/com/poortorich/ranking/response/AllRankingsResponse.java
  src/main/java/com/poortorich/ranking/response/RankingInfoResponse.java
  src/main/java/com/poortorich/ranking/response/enums/RankingResponse.java
  src/main/java/com/poortorich/ranking/service/RankingService.java
  src/test/java/com/poortorich/chat/service/ChatParticipantServiceTest.java
  src/test/java/com/poortorich/ranking/controller/RankingControllerTest.java
  src/test/java/com/poortorich/ranking/service/RankingServiceTest.java
Labels: ✨Feature, 📬API

#496 [#494] 사진 상세 조회 API 구현
  src/main/java/com/poortorich/photo/constants/PhotoResponseMessage.java
  src/main/java/com/poortorich/photo/controller/PhotoController.java
  src/main/java/com/poortorich/photo/facade/PhotoFacade.java
  src/main/java/com/poortorich/photo/repository/PhotoRepository.java
  src/main/java/com/poortorich/photo/response/PhotoDetailsResponse.java
  src/main/java/com/poortorich/photo/response/UploadedUserResponse.java
  src/main/java/com/poortorich/photo/response/enums/PhotoResponse.java
  src/main/java/com/poortorich/photo/service/PhotoService.java
  src/main/java/com/poortorich/photo/util/PhotoBuilder.java
  src/test/java/com/poortorich/photo/controller/PhotoControllerTest.java
  src/test/java/com/poortorich/photo/facade/PhotoFacadeTest.java
  src/test/java/com/poortorich/photo/service/PhotoServiceTest.java
Labels: ✨Feature, 📬API
