Repository Poor-To-Rich/backend, pull requests merged in 2025-03, with the labels that each got.

#9 Feat/#1
  build.gradle
  src/main/java/PoorToRich/PoorToRich/email/config/emailConfig.java
  src/main/java/PoorToRich/PoorToRich/email/controller/MailController.java
  src/main/java/PoorToRich/PoorToRich/email/enums/EmailResponse.java
  src/main/java/PoorToRich/PoorToRich/email/enums/EmailTemplateType.java
  src/main/java/PoorToRich/PoorToRich/email/facade/EmailFacade.java
  src/main/java/PoorToRich/PoorToRich/email/request/EmailVerificationRequest.java
  src/main/java/PoorToRich/PoorToRich/email/service/EmailVerificationService.java
  src/main/java/PoorToRich/PoorToRich/email/service/MailService.java
  src/main/java/PoorToRich/PoorToRich/email/util/VerificationCodeGenerator.java
  src/main/java/PoorToRich/PoorToRich/global/response/BaseResponse.java
  src/main/java/PoorToRich/PoorToRich/global/response/Response.java
  src/main/resources/application.properties
Labels: ✨Feature, 🌏Deploy, ⚙️Setting, 📬API

#13 fix: 카테고리 import 수정
  src/main/java/PoorToRich/PoorToRich/category/entity/Category.java
Labels: 🐞BugFix

#14 Feat/#10
  src/main/java/PoorToRich/PoorToRich/PoorToRichApplication.java
  src/main/java/PoorToRich/PoorToRich/category/entity/Category.java
  src/main/java/PoorToRich/PoorToRich/email/controller/MailController.java
  src/main/java/PoorToRich/PoorToRich/email/enums/EmailResponse.java
  src/main/java/PoorToRich/PoorToRich/email/enums/EmailTemplateType.java
  src/main/java/PoorToRich/PoorToRich/email/handler/EmailExceptionHandler.java
  src/main/java/PoorToRich/PoorToRich/email/request/EmailVerificationRequest.java
  src/main/java/PoorToRich/PoorToRich/email/service/MailService.java
  src/main/java/PoorToRich/PoorToRich/global/exceptions/AuthenticationException.java
  src/main/java/PoorToRich/PoorToRich/global/exceptions/AuthorizationException.java
  src/main/java/PoorToRich/PoorToRich/global/exceptions/BadRequestException.java
  src/main/java/PoorToRich/PoorToRich/global/exceptions/ConflictException.java
  src/main/java/PoorToRich/PoorToRich/global/exceptions/InternalServerErrorException.java
  src/main/java/PoorToRich/PoorToRich/global/exceptions/NotFoundException.java
  src/main/java/PoorToRich/PoorToRich/global/exceptions/UnauthorizedException.java
  src/main/java/PoorToRich/PoorToRich/global/handler/GlobalExceptionHandler.java
  src/main/java/PoorToRich/PoorToRich/global/response/BaseResponse.java
Labels: 🐞BugFix, ✨Feature, 📬API

#15 Feat/#11
  src/main/java/PoorToRich/PoorToRich/category/controller/CategoryController.java
  src/main/java/PoorToRich/PoorToRich/category/response/DefaultCategoriesResponse.java
  src/main/java/PoorToRich/PoorToRich/category/response/DefaultCategoryResponse.java
  src/main/java/PoorToRich/PoorToRich/category/service/CategoryService.java
Labels: ✨Feature, 📬API

#17 Feat/#16
  src/main/java/PoorToRich/PoorToRich/category/controller/CategoryController.java
  src/main/java/PoorToRich/PoorToRich/category/response/CustomCategoriesResponse.java
  src/main/java/PoorToRich/PoorToRich/category/response/CustomCategoryResponse.java
  src/main/java/PoorToRich/PoorToRich/category/service/CategoryService.java
Labels: ✨Feature, 🛠️Refactor, 📬API

#20 Feat/#19
  src/main/java/PoorToRich/PoorToRich/category/controller/CategoryController.java
Labels: ✨Feature, 📬API

#24 Feat/#21
  src/main/java/PoorToRich/PoorToRich/category/controller/CategoryController.java
  src/main/java/PoorToRich/PoorToRich/category/entity/Category.java
  src/main/java/PoorToRich/PoorToRich/category/request/CustomCategoryRequest.java
  src/main/java/PoorToRich/PoorToRich/category/response/CategoryResponse.java
  src/main/java/PoorToRich/PoorToRich/category/service/CategoryService.java
  src/main/java/PoorToRich/PoorToRich/category/validator/CategoryValidator.java
Labels: ✨Feature, 🛠️Refactor, 📬API

#25 feat: 인증 코드 재발급 횟수 조회 API
  src/main/java/PoorToRich/PoorToRich/email/controller/MailController.java
  src/main/java/PoorToRich/PoorToRich/email/enums/EmailResponse.java
  src/main/java/PoorToRich/PoorToRich/email/facade/EmailFacade.java
  src/main/java/PoorToRich/PoorToRich/email/response/VerificationResendCodeStatusResponse.java
  src/main/java/PoorToRich/PoorToRich/email/service/EmailVerificationService.java
Labels: ✨Feature, 📬API

#29 Feat/#28
  src/main/java/com/poortorich/category/controller/CategoryController.java
  src/main/java/com/poortorich/email/controller/MailController.java
  src/main/java/com/poortorich/email/facade/EmailFacade.java
  src/main/java/com/poortorich/email/response/VerificationResendCodeStatusResponse.java
Labels: ✨Feature, 🛠️Refactor, 📬API

#31 [#30] 카테고리 조회 API 구현
  src/main/java/com/poortorich/PoorToRichApplication.java
  src/main/java/com/poortorich/category/controller/CategoryController.java
  src/main/java/com/poortorich/category/repository/CategoryRepository.java
  src/main/java/com/poortorich/category/request/CategoryInfoRequest.java
  src/main/java/com/poortorich/category/response/CategoryInfoResponse.java
  src/main/java/com/poortorich/category/response/CategoryResponse.java
  src/main/java/com/poortorich/category/service/CategoryService.java
Labels: ✨Feature, 🛠️Refactor, 📬API

#33 [#32] 카테고리 편집 API 구현
  src/main/java/com/poortorich/category/controller/CategoryController.java
  src/main/java/com/poortorich/category/entity/Category.java
  src/main/java/com/poortorich/category/response/CategoryResponse.java
  src/main/java/com/poortorich/category/service/CategoryService.java
  src/main/java/com/poortorich/category/validator/CategoryValidator.java
Labels: ✨Feature, 📬API

#40 Feat/#39
  build.gradle
  src/main/java/com/poortorich/s3/constants/S3ResponseMessages.java
  src/main/java/com/poortorich/s3/constants/S3ValidationConstraints.java
  src/main/java/com/poortorich/s3/contoller/FileUploadController.java
  src/main/java/com/poortorich/s3/response/enums/S3Response.java
  src/main/java/com/poortorich/s3/service/FileUploadService.java
  src/main/java/com/poortorich/s3/util/S3FileUtils.java
  src/main/java/com/poortorich/s3/validator/FileValidator.java
  src/test/java/com/poortorich/s3/constants/S3TestConfig.java
  src/test/java/com/poortorich/s3/constants/S3TestExceptionMessages.java
  src/test/java/com/poortorich/s3/constants/S3TestFile.java
  src/test/java/com/poortorich/s3/service/FileUploadServiceTest.java
  src/test/java/com/poortorich/s3/util/S3FileUtilsTest.java
  src/test/java/com/poortorich/s3/util/S3TestFileGenerator.java
  src/test/java/com/poortorich/s3/validator/FileValidatorTest.java
Labels: ✨Feature, 🌏Deploy, ⚙️Setting, ✔️Test, 📬API
